cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED RUN_DIR)
    message(FATAL_ERROR "Missing RUN_DIR")
endif()
if(NOT EXISTS "${RUN_DIR}/snapshot.json")
    message(FATAL_ERROR "Missing runtime snapshot")
endif()
file(READ "${RUN_DIR}/snapshot.json" snapshot)
string(JSON schema GET "${snapshot}" schema_version)
string(JSON version GET "${snapshot}" savegame_version)
string(JSON width GET "${snapshot}" map width)
string(JSON height GET "${snapshot}" map height)
string(JSON tiles LENGTH "${snapshot}" map tiles)
math(EXPR expected "${width} * ${height}")
if(NOT schema EQUAL 1 OR NOT version EQUAL 362 OR NOT tiles EQUAL expected)
    message(FATAL_ERROR "Invalid snapshot schema/version/map size")
endif()
string(JSON dates LENGTH "${snapshot}" date)
string(JSON settings LENGTH "${snapshot}" settings)
string(JSON owners LENGTH "${snapshot}" script_random)
if(NOT dates EQUAL 17 OR NOT settings EQUAL 195 OR NOT owners EQUAL 19)
    message(FATAL_ERROR "Incomplete runtime descriptor extraction: DATE=${dates}, PATS=${settings}, SRND=${owners}")
endif()
file(SIZE "${RUN_DIR}/save/autosave/exit.sav" saved_size)
if(saved_size EQUAL 0)
    message(FATAL_ERROR "Missing paired native save")
endif()
message(STATUS "PASS runtime snapshot: ${tiles} tiles, ${dates} DATE fields, ${settings} PATS fields, ${owners} owners, ${saved_size} native save bytes")
