cmake_minimum_required(VERSION 3.20)
foreach(required ORACLE RUN_DIR CONFIG INPUT)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/check-replay-build.cmake")
get_filename_component(RUN_DIR "${RUN_DIR}" ABSOLUTE)
if(EXISTS "${RUN_DIR}/content.json" OR EXISTS "${RUN_DIR}/invocation.txt")
    message(FATAL_ERROR "Stale content oracle output: ${RUN_DIR}")
endif()
if(DEFINED ENV{OTTD_REPLAY_PATH})
    message(FATAL_ERROR "Content observer requires a dedicated after-load invocation")
endif()
file(MAKE_DIRECTORY "${RUN_DIR}")
file(SHA256 "${ORACLE}" oracle_hash)
file(SHA256 "${INPUT}" input_hash)
file(SHA256 "${CONFIG}" config_hash)
file(WRITE "${RUN_DIR}/invocation.txt" "ORACLE=${ORACLE}\nORACLE_SHA256=${oracle_hash}\nINPUT=${INPUT}\nINPUT_SHA256=${input_hash}\nCONFIG=${CONFIG}\nCONFIG_SHA256=${config_hash}\nUPSTREAM=14ec60f248547d4d062a1160f0fc26d742319888\nPHASE=after-load\n")
set(ENV{OTTD_CONTENT_PATH} "${RUN_DIR}/content.json")
set(TICKS 1)
include("${CMAKE_CURRENT_LIST_DIR}/run-reference.cmake")
if(NOT EXISTS "${RUN_DIR}/content.json")
    message(FATAL_ERROR "Native content observation missing")
endif()
file(READ "${RUN_DIR}/content.json" content)
string(JSON engines LENGTH "${content}" engines)
string(JSON cargo LENGTH "${content}" cargo)
string(JSON prices LENGTH "${content}" prices values)
if(NOT engines EQUAL 256 OR NOT cargo EQUAL 64 OR NOT prices EQUAL 71)
    message(FATAL_ERROR "Incomplete native content observation")
endif()
file(READ "${RUN_DIR}/stderr.log" native_log)
if(native_log MATCHES "\\[grf:0\\]")
    message(FATAL_ERROR "Native content warning")
endif()
message(STATUS "PASS passive native content observation")
