cmake_minimum_required(VERSION 3.20)
foreach(required ORACLE RUN_DIR INPUT)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
get_filename_component(RUN_DIR "${RUN_DIR}" ABSOLUTE)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(EXISTS "${RUN_DIR}")
    message(FATAL_ERROR "GameScript run directory must be fresh")
endif()
if(NOT RELOAD AND NOT INPUT STREQUAL "GENERATE")
    message(FATAL_ERROR "Initial GameScript fixture must generate its configured world")
endif()
if(RELOAD AND INPUT STREQUAL "GENERATE")
    message(FATAL_ERROR "GameScript reload requires an existing save")
endif()
file(MAKE_DIRECTORY "${RUN_DIR}/game" "${RUN_DIR}/scripts")
file(COPY "${ROOT}/fixtures/world/world-game" DESTINATION "${RUN_DIR}/game")
file(READ "${ROOT}/scripts/reference.cfg" config)
string(REPLACE "savegame_format = none" "savegame_format = zlib" config "${config}")
string(APPEND config "\n[game_scripts]\nWorldGame =\n")
file(WRITE "${RUN_DIR}/fixture.cfg" "${config}")
file(WRITE "${RUN_DIR}/scripts/game_start.scr" "debug_level script=2,sl=2\n")
set(CONFIG "${RUN_DIR}/fixture.cfg")
set(TICKS 1000)
file(COPY_FILE "${CONFIG}" "${RUN_DIR}/openttd.cfg")
set(ENV{OTTD_WORLD_PATH} "${RUN_DIR}/world.json")
set(ENV{OTTD_WORLD_DERIVED_PATH} "${RUN_DIR}/derived.json")
set(ENV{OTTD_WORLD_SCHEMA_PATH} "${RUN_DIR}/schema.json")
file(SHA256 "${ORACLE}" oracle_hash)
file(WRITE "${RUN_DIR}/invocation.txt" "ORACLE=${ORACLE}\nORACLE_SHA256=${oracle_hash}\nINPUT=${INPUT}\nTICKS=${TICKS}\nDEBUG=sl=2,script=2\n")
if(INPUT STREQUAL "GENERATE")
    set(game_args -g -G 12345)
    set(expected_loads 1)
else()
    if(NOT EXISTS "${INPUT}")
        message(FATAL_ERROR "Missing GameScript input save")
    endif()
    file(SHA256 "${INPUT}" input_hash)
    file(APPEND "${RUN_DIR}/invocation.txt" "INPUT_SHA256=${input_hash}\n")
    set(game_args -g "${INPUT}")
    set(expected_loads 2)
endif()
execute_process(
    COMMAND "${ORACLE}" -X -x -c "${RUN_DIR}/openttd.cfg"
        "-vnull:ticks=${TICKS}" -snull -mnull ${game_args} -d sl=2,script=2
    WORKING_DIRECTORY "${RUN_DIR}"
    OUTPUT_FILE "${RUN_DIR}/stdout.log"
    ERROR_FILE "${RUN_DIR}/stderr.log"
    RESULT_VARIABLE result TIMEOUT 60
)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Native GameScript run failed (${result})")
endif()
file(READ "${RUN_DIR}/stderr.log" log)
string(REGEX MATCHALL "Loading savegame version [0-9]+" loaded "${log}")
list(LENGTH loaded loads)
if(NOT loads EQUAL expected_loads OR log MATCHES "\\[sl:0\\]")
    message(FATAL_ERROR "Native GameScript run failed load/fallback controls")
endif()
foreach(artifact world.json schema.json save/autosave/exit.sav)
    if(NOT EXISTS "${RUN_DIR}/${artifact}")
        message(FATAL_ERROR "Native GameScript run missing ${artifact}")
    endif()
endforeach()
if(RELOAD AND NOT EXISTS "${RUN_DIR}/derived.json")
    message(FATAL_ERROR "Native GameScript reload missing structural state")
endif()
if(RELOAD)
    if(NOT log MATCHES "WORLD_GAME_RESTORED marker=362 wide=9007199254740993")
        message(FATAL_ERROR "GameScript did not restore its nested saved marker and object IDs")
    endif()
else()
    if(NOT log MATCHES "WORLD_GAME_READY marker=362 goal=[0-9]+ page=[0-9]+ league=[0-9]+")
        message(FATAL_ERROR "GameScript fixture did not complete its checked native commands")
    endif()
endif()
file(READ "${RUN_DIR}/world.json" world)
string(JSON version GET "${world}" savegame_version)
string(JSON chunks LENGTH "${world}" chunks)
if(NOT version EQUAL 362 OR NOT chunks EQUAL 62)
    message(FATAL_ERROR "Native GameScript output has unexpected version/chunk inventory")
endif()
foreach(chunk GOAL STPA STPE LEAT LEAE)
    string(JSON count LENGTH "${world}" chunks ${chunk} records)
    if(count LESS 1)
        message(FATAL_ERROR "GameScript fixture has empty ${chunk} pool")
    endif()
endforeach()
string(JSON script_bytes LENGTH "${world}" chunks GSDT records 0 script_data)
if(script_bytes LESS 20)
    message(FATAL_ERROR "GameScript fixture has no meaningful saved script data")
endif()
message(STATUS "PASS native GameScript saved state and ancillary pools")
