cmake_minimum_required(VERSION 3.20)
foreach(required ORACLE RUN_DIR CONFIG INPUT MANIFEST)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/check-replay-build.cmake")
if(DEFINED ENV{OTTD_REPLAY_PATH})
    message(FATAL_ERROR "GRF load control requires a dedicated invocation")
endif()
if(INPUT STREQUAL "GENERATE")
    message(FATAL_ERROR "GRF load control requires an explicit saved-game load")
endif()
get_filename_component(RUN_DIR "${RUN_DIR}" ABSOLUTE)
if(EXISTS "${RUN_DIR}")
    message(FATAL_ERROR "GRF control run directory already exists")
endif()
file(MAKE_DIRECTORY "${RUN_DIR}")
file(SHA256 "${ORACLE}" oracle_hash)
file(SHA256 "${MANIFEST}" manifest_hash)
file(SHA256 "${CONFIG}" config_hash)
file(SHA256 "${INPUT}" input_hash)
file(WRITE "${RUN_DIR}/invocation.txt" "ORACLE=${ORACLE}\nORACLE_SHA256=${oracle_hash}\nMANIFEST=${MANIFEST}\nMANIFEST_SHA256=${manifest_hash}\nINPUT=${INPUT}\nINPUT_SHA256=${input_hash}\nCONFIG_SHA256=${config_hash}\nUPSTREAM=14ec60f248547d4d062a1160f0fc26d742319888\nPHASE=one-shot-AfterLoadGame-GfxLoadSprites-LoadNewGRF\nSCOPE=configured-test-files-after-original-baseline-registry\n")
file(READ "${MANIFEST}" manifest)
string(JSON count LENGTH "${manifest}" files)
if(count GREATER 0)
    math(EXPR last "${count} - 1")
    foreach(index RANGE 0 ${last})
        string(JSON path GET "${manifest}" files ${index} path)
        if(EXISTS "${path}")
            file(SHA256 "${path}" source_hash)
            file(APPEND "${RUN_DIR}/inputs.sha256" "${source_hash}  ${path}\n")
        else()
            file(APPEND "${RUN_DIR}/inputs.sha256" "MISSING  ${path}\n")
        endif()
    endforeach()
endif()
set(ENV{OTTD_GRF_CONTROL_MANIFEST} "${MANIFEST}")
set(ENV{OTTD_GRF_CONTROL_OUTPUT} "${RUN_DIR}/control.json")
set(TICKS 1)
include("${CMAKE_CURRENT_LIST_DIR}/run-reference.cmake")
file(READ "${RUN_DIR}/control.json" observation)
string(JSON arms GET "${observation}" arms)
string(JSON consumptions GET "${observation}" consumptions)
string(JSON baseline GET "${observation}" baseset_count)
string(JSON baseline_count LENGTH "${observation}" baseline_sources)
if(NOT baseline_count EQUAL 2)
    message(FATAL_ERROR "Missing original baseline source paths")
endif()
foreach(index RANGE 0 1)
    string(JSON baseline_path GET "${observation}" baseline_sources ${index})
    file(SHA256 "${baseline_path}" baseline_hash)
    file(APPEND "${RUN_DIR}/baseline-inputs.sha256" "${baseline_hash}  ${baseline_path}\n")
endforeach()
string(JSON observed LENGTH "${observation}" files)
math(EXPR expected "${count} + ${baseline}")
if(NOT arms EQUAL 1 OR NOT consumptions EQUAL 1 OR NOT baseline EQUAL 2 OR NOT observed EQUAL expected)
    message(FATAL_ERROR "GRF control observer did not consume exactly the target original load")
endif()
message(STATUS "PASS original LoadNewGRF observations: ${count} test configs, ${baseline} preserved baselines")
