cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED RUN_DIR)
    message(FATAL_ERROR "Missing RUN_DIR")
endif()
get_filename_component(RUN_DIR "${RUN_DIR}" ABSOLUTE)
if(EXISTS "${RUN_DIR}/world.json" OR EXISTS "${RUN_DIR}/derived.json" OR EXISTS "${RUN_DIR}/schema.json")
    message(FATAL_ERROR "Run directory contains stale world oracle output: ${RUN_DIR}")
endif()
set(ENV{OTTD_WORLD_PATH} "${RUN_DIR}/world.json")
set(ENV{OTTD_WORLD_DERIVED_PATH} "${RUN_DIR}/derived.json")
set(ENV{OTTD_WORLD_SCHEMA_PATH} "${RUN_DIR}/schema.json")
file(MAKE_DIRECTORY "${RUN_DIR}")
file(SHA256 "${ORACLE}" oracle_hash)
file(WRITE "${RUN_DIR}/invocation.txt" "ORACLE=${ORACLE}\nORACLE_SHA256=${oracle_hash}\nCONFIG=${CONFIG}\nINPUT=${INPUT}\nTICKS=${TICKS}\nOTTD_WORLD_PATH=${RUN_DIR}/world.json\nOTTD_WORLD_DERIVED_PATH=${RUN_DIR}/derived.json\nOTTD_WORLD_SCHEMA_PATH=${RUN_DIR}/schema.json\nDRIVER=${CMAKE_CURRENT_LIST_FILE}\n")
if(NOT INPUT STREQUAL "GENERATE" AND EXISTS "${INPUT}")
    file(SHA256 "${INPUT}" input_hash)
    file(APPEND "${RUN_DIR}/invocation.txt" "INPUT_SHA256=${input_hash}\n")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/run-reference.cmake")
file(READ "${RUN_DIR}/stderr.log" native_log)
if(native_log MATCHES "\\[grf:0\\]")
    message(FATAL_ERROR "Native world oracle reported a content warning")
endif()
if(NOT EXISTS "${RUN_DIR}/world.json")
    message(FATAL_ERROR "Reference engine did not emit world.json")
endif()
file(READ "${RUN_DIR}/world.json" world)
string(JSON schema GET "${world}" schema_version)
string(JSON version GET "${world}" savegame_version)
string(JSON chunks LENGTH "${world}" chunks)
if(NOT schema EQUAL 1 OR NOT version EQUAL 362 OR NOT chunks EQUAL 62)
    message(FATAL_ERROR "Unexpected world oracle schema, version, or chunk inventory")
endif()
message(STATUS "PASS native persisted world: ${chunks} chunks")
if(NOT INPUT STREQUAL "GENERATE" AND NOT EXISTS "${RUN_DIR}/derived.json")
    message(FATAL_ERROR "Reference engine did not emit derived.json")
endif()
if(NOT EXISTS "${RUN_DIR}/schema.json")
    message(FATAL_ERROR "Reference engine did not emit schema.json")
endif()
file(READ "${RUN_DIR}/schema.json" metadata)
string(JSON tables LENGTH "${metadata}" chunks)
if(NOT tables EQUAL 52)
    message(FATAL_ERROR "Unexpected native world table schema inventory")
endif()
