cmake_minimum_required(VERSION 3.20)
foreach(required ORACLE RUN_DIR CONFIG INPUT GRF)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/check-replay-build.cmake")
if(DEFINED ENV{OTTD_REPLAY_PATH})
    message(FATAL_ERROR "GRF scan requires a dedicated invocation")
endif()
get_filename_component(RUN_DIR "${RUN_DIR}" ABSOLUTE)
if(EXISTS "${RUN_DIR}")
    message(FATAL_ERROR "GRF scan run directory already exists")
endif()
file(MAKE_DIRECTORY "${RUN_DIR}")
file(SHA256 "${ORACLE}" oracle_hash)
file(SHA256 "${GRF}" grf_hash)
file(SHA256 "${CONFIG}" config_hash)
file(SHA256 "${INPUT}" input_hash)
file(WRITE "${RUN_DIR}/invocation.txt" "ORACLE=${ORACLE}\nORACLE_SHA256=${oracle_hash}\nGRF=${GRF}\nGRF_SHA256=${grf_hash}\nINPUT=${INPUT}\nINPUT_SHA256=${input_hash}\nCONFIG_SHA256=${config_hash}\nUPSTREAM=14ec60f248547d4d062a1160f0fc26d742319888\nPHASE=dedicated-filescan-after-load\nTRACE=${TRACE}\n")
set(ENV{OTTD_GRF_SCAN_INPUT} "${GRF}")
set(ENV{OTTD_GRF_SCAN_OUTPUT} "${RUN_DIR}/scan.json")
unset(ENV{OTTD_GRF_SCAN_TRACE})
if(TRACE)
    set(ENV{OTTD_GRF_SCAN_TRACE} "1")
endif()
set(TICKS 1)
include("${CMAKE_CURRENT_LIST_DIR}/run-reference.cmake")
file(READ "${RUN_DIR}/scan.json" scan)
string(JSON status GET "${scan}" status)
if(NOT status EQUAL 0 AND NOT status EQUAL 1)
    message(FATAL_ERROR "Unexpected FILESCAN status ${status}")
endif()
message(STATUS "PASS original native FILESCAN observation")
