cmake_minimum_required(VERSION 3.20)
foreach(required ORACLE RUN_DIR CONFIG INPUT MANIFEST)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/check-replay-build.cmake")
if(DEFINED ENV{OTTD_REPLAY_PATH} OR DEFINED ENV{OTTD_GRF_CURRENCY_CASE})
    message(FATAL_ERROR "Currency probe refuses replay or case subset")
endif()
get_filename_component(RUN_DIR "${RUN_DIR}" ABSOLUTE)
set(ENV{OTTD_GRF_CURRENCY_OUTPUT} "${RUN_DIR}/currency.json")
include("${CMAKE_CURRENT_LIST_DIR}/check-grf-language-reference.cmake")
file(READ "${RUN_DIR}/currency.json" observation)
string(JSON mode GET "${observation}" mode)
string(JSON arms GET "${observation}" arms)
string(JSON consumptions GET "${observation}" consumptions)
file(READ "${MANIFEST}" currency_manifest)
string(JSON api ERROR_VARIABLE absent GET "${currency_manifest}" currency_api)
if(absent)
    set(expected_mode "actual-loader-currency-owners")
else()
    set(expected_mode "separate-process-original-currency-api")
endif()
string(JSON reload ERROR_VARIABLE no_reload GET "${currency_manifest}" currency_reload)
if(no_reload)
    set(expected_consumptions 1)
else()
    set(expected_consumptions 2)
endif()
if(NOT mode STREQUAL expected_mode OR NOT arms EQUAL 1 OR NOT consumptions EQUAL expected_consumptions)
    message(FATAL_ERROR "Wrong original currency invocation")
endif()
message(STATUS "PASS original currency witness: ${mode}, loads=${consumptions}")
