cmake_minimum_required(VERSION 3.20)
foreach(required ORACLE RUN_DIR CONFIG INPUT)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/check-replay-build.cmake")
if(DEFINED ENV{OTTD_REPLAY_PATH})
    message(FATAL_ERROR "Road runtime observer requires a dedicated after-load invocation")
endif()
get_filename_component(RUN_DIR "${RUN_DIR}" ABSOLUTE)
if(EXISTS "${RUN_DIR}")
    message(FATAL_ERROR "Road runtime run directory must be fresh")
endif()
file(MAKE_DIRECTORY "${RUN_DIR}")
file(SHA256 "${ORACLE}" oracle_hash)
file(SHA256 "${INPUT}" input_hash)
file(SHA256 "${CONFIG}" config_hash)
unset(ENV{OTTD_RUNTIME_ROAD_PREPARE})
unset(ENV{OTTD_RUNTIME_ROAD_PATH})
if(PREPARE)
    set(phase native-fixture-preparation)
    set(ENV{OTTD_RUNTIME_ROAD_PREPARE} "${RUN_DIR}/fixture.txt")
else()
    set(phase after-load)
    set(ENV{OTTD_RUNTIME_ROAD_PATH} "${RUN_DIR}/runtime.json")
endif()
file(WRITE "${RUN_DIR}/invocation.txt" "ORACLE=${ORACLE}\nORACLE_SHA256=${oracle_hash}\nINPUT=${INPUT}\nINPUT_SHA256=${input_hash}\nCONFIG=${CONFIG}\nCONFIG_SHA256=${config_hash}\nUPSTREAM=14ec60f248547d4d062a1160f0fc26d742319888\nPHASE=${phase}\n")
set(TICKS 1)
include("${CMAKE_CURRENT_LIST_DIR}/run-reference.cmake")
if(PREPARE)
    if(NOT EXISTS "${RUN_DIR}/fixture.txt")
        message(FATAL_ERROR "Native road fixture manifest missing")
    endif()
else()
    file(READ "${RUN_DIR}/runtime.json" runtime)
    string(JSON roads LENGTH "${runtime}" road)
    string(JSON saved LENGTH "${runtime}" saved)
    if(roads LESS 6 OR NOT roads EQUAL saved)
        message(FATAL_ERROR "Incomplete native road runtime observation")
    endif()
endif()
file(READ "${RUN_DIR}/stderr.log" native_log)
if(native_log MATCHES "\\[grf:0\\]")
    message(FATAL_ERROR "Native road runtime reported a content warning")
endif()
message(STATUS "PASS native road ${phase}")
