cmake_minimum_required(VERSION 3.20)
foreach(required ORACLE RUN_DIR CONFIG INPUT MANIFEST)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/check-replay-build.cmake")
foreach(variable OTTD_CARGO_IDENTITY_OUTPUT OTTD_ENGINE_SPECS_OUTPUT OTTD_REPLAY_PATH OTTD_GRF_CURRENCY_OUTPUT OTTD_GRF_STRINGS_OUTPUT OTTD_MOVEMENT_OBSERVE OTTD_MOVEMENT_PREPARE)
    if(DEFINED ENV{${variable}})
        message(FATAL_ERROR "Cargo-identity probe refuses mixed environment: ${variable}")
    endif()
endforeach()
file(SIZE "${MANIFEST}" manifest_bytes)
if(manifest_bytes GREATER 65536)
    message(FATAL_ERROR "Cargo-identity host manifest byte budget")
endif()
file(READ "${MANIFEST}" manifest)
string(JSON mode GET "${manifest}" cargo_identity mode)
if(NOT mode STREQUAL "api" AND NOT mode STREQUAL "load")
    message(FATAL_ERROR "Cargo-identity mode must be api or load")
endif()
file(SHA256 "${INPUT}" input_hash)
file(SHA256 "${root}/fixtures/replay/clear-v362.sav" fixture_hash)
if(NOT input_hash STREQUAL fixture_hash)
    message(FATAL_ERROR "Cargo-identity initial pilot requires exact clear-v362 fixture")
endif()
get_filename_component(RUN_DIR "${RUN_DIR}" ABSOLUTE)
if(EXISTS "${RUN_DIR}")
    message(FATAL_ERROR "Cargo-identity run directory must be fresh")
endif()
file(MAKE_DIRECTORY "${RUN_DIR}")
file(COPY_FILE "${CONFIG}" "${RUN_DIR}/openttd.cfg")
file(SHA256 "${ORACLE}" oracle_hash)
file(SHA256 "${MANIFEST}" manifest_hash)
file(SHA256 "${CONFIG}" config_hash)
file(WRITE "${RUN_DIR}/invocation.txt" "ORACLE=${ORACLE}\nORACLE_SHA256=${oracle_hash}\nMANIFEST=${MANIFEST}\nMANIFEST_SHA256=${manifest_hash}\nINPUT=${INPUT}\nINPUT_SHA256=${input_hash}\nCONFIG_SHA256=${config_hash}\nUPSTREAM=14ec60f248547d4d062a1160f0fc26d742319888\nMODE=${mode}\n")
foreach(source scripts/check-cargo-identity-reference.cmake scripts/check-replay-build.cmake scripts/setup-snapshot-reference.sh scripts/run-reference.cmake reference/cargo_identity.hpp reference/cargo_identity_admission.hpp reference/cargo_identity_state.hpp reference/cargo_identity_hooks.hpp reference/cargo_identity.patch reference/engine_specs.hpp reference/grf_load_control.hpp)
    file(SHA256 "${root}/${source}" source_hash)
    file(APPEND "${RUN_DIR}/invocation.txt" "SOURCE_SHA256=${source_hash} ${source}\n")
endforeach()
string(JSON count LENGTH "${manifest}" files)
if(count GREATER 0)
    math(EXPR last "${count} - 1")
    foreach(index RANGE 0 ${last})
        string(JSON path GET "${manifest}" files ${index} path)
        file(SIZE "${path}" configured_bytes)
        if(configured_bytes GREATER 4096)
            message(FATAL_ERROR "Cargo-identity host configured-file byte budget")
        endif()
        file(SHA256 "${path}" source_hash)
        file(APPEND "${RUN_DIR}/inputs.sha256" "${source_hash}  ${path}\n")
    endforeach()
else()
    file(WRITE "${RUN_DIR}/inputs.sha256" "NO_CONFIGURED_FILES\n")
endif()
set(ENV{OTTD_GRF_CONTROL_MANIFEST} "${MANIFEST}")
set(ENV{OTTD_GRF_CONTROL_OUTPUT} "${RUN_DIR}/control.json")
set(ENV{OTTD_CARGO_IDENTITY_OUTPUT} "${RUN_DIR}/cargo.json")
execute_process(COMMAND "${ORACLE}" -X -x -c "${RUN_DIR}/openttd.cfg" -vnull:ticks=1 -snull -mnull -g "${INPUT}" -d sl=2
    WORKING_DIRECTORY "${RUN_DIR}" OUTPUT_FILE "${RUN_DIR}/stdout.log" ERROR_FILE "${RUN_DIR}/stderr.log"
    RESULT_VARIABLE result TIMEOUT 60)
file(WRITE "${RUN_DIR}/native-status.json" "\"${result}\"\n")
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Cargo-identity native invocation failed: ${result}")
endif()
if(mode STREQUAL "load" AND NOT EXISTS "${RUN_DIR}/save/autosave/exit.sav")
    message(FATAL_ERROR "Cargo-identity loader did not complete saved-game load")
endif()
file(READ "${RUN_DIR}/stderr.log" engine_log)
if(engine_log MATCHES "\\[sl:0\\]")
    message(FATAL_ERROR "Cargo-identity native save/load error")
endif()
string(REGEX MATCHALL "Loading savegame version [0-9]+" loaded_versions "${engine_log}")
list(LENGTH loaded_versions load_count)
if(NOT load_count EQUAL 2)
    message(FATAL_ERROR "Cargo-identity unexpected game-load count")
endif()
if(mode STREQUAL "api" AND EXISTS "${RUN_DIR}/save/autosave/exit.sav")
    message(FATAL_ERROR "Cargo-identity API unexpectedly advanced the world")
endif()
file(READ "${RUN_DIR}/control.json" control)
file(READ "${RUN_DIR}/cargo.json" specs)
string(JSON arms GET "${specs}" arms)
string(JSON consumptions GET "${specs}" consumptions)
string(JSON observed_mode GET "${specs}" mode)
if(mode STREQUAL "api")
    set(expected_mode "original-cargo-identity-api-v1")
else()
    set(expected_mode "actual-loader-cargo-identity-v1")
endif()
if(NOT arms EQUAL 1 OR NOT consumptions EQUAL 1 OR NOT observed_mode STREQUAL expected_mode)
    message(FATAL_ERROR "Cargo-identity observation invocation mismatch")
endif()
string(JSON control_baseline GET "${control}" baseline_sources)
string(JSON spec_baseline GET "${specs}" baseline_sources)
if(NOT control_baseline STREQUAL spec_baseline)
    message(FATAL_ERROR "Cargo-identity ordered baseline binding mismatch")
endif()
foreach(index RANGE 0 1)
    string(JSON path GET "${control}" baseline_sources ${index})
    file(SHA256 "${path}" source_hash)
    file(APPEND "${RUN_DIR}/baseline-inputs.sha256" "${source_hash}  ${path}\n")
endforeach()
message(STATUS "OBSERVED original cargo-identity pilot ${mode}; Rust parity not evaluated")
