cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED RUN_DIR)
    message(FATAL_ERROR "Missing RUN_DIR")
endif()
get_filename_component(RUN_DIR "${RUN_DIR}" ABSOLUTE)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(EXISTS "${RUN_DIR}")
    message(FATAL_ERROR "Fixture run directory must be fresh")
endif()
file(MAKE_DIRECTORY "${RUN_DIR}")
file(READ "${ROOT}/scripts/reference.cfg" config)
string(REPLACE "savegame_format = none" "savegame_format = zlib" config "${config}")
file(WRITE "${RUN_DIR}/fixture.cfg" "${config}")
set(CONFIG "${RUN_DIR}/fixture.cfg")
set(INPUT "${ROOT}/fixtures/upstream-stationlist-v211.sav")
set(TICKS 1)
include("${CMAKE_CURRENT_LIST_DIR}/check-world-reference.cmake")
