cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED RUN_DIR)
    message(FATAL_ERROR "Missing RUN_DIR")
endif()
file(READ "${RUN_DIR}/process.txt" process)
if(NOT process STREQUAL "exit=0\n")
    message(FATAL_ERROR "Native process evidence is not successful")
endif()
file(READ "${RUN_DIR}/stderr.log" native_log)
if(native_log MATCHES "\\[(sl|grf):0\\]")
    message(FATAL_ERROR "Native replay reported a save/load/content error")
endif()
string(REGEX MATCHALL "Loading savegame version [0-9]+" loaded_versions "${native_log}")
list(LENGTH loaded_versions load_count)
if(NOT load_count EQUAL 2)
    message(FATAL_ERROR "Native replay loaded ${load_count} games; expected title plus requested input")
endif()
if(NOT EXISTS "${RUN_DIR}/results.json")
    message(FATAL_ERROR "Native replay did not emit results.json")
endif()
file(READ "${RUN_DIR}/results.json" results)
file(READ "${RUN_DIR}/actions.json" actions)
string(JSON version GET "${results}" schema_version)
string(JSON observed LENGTH "${results}" actions)
string(JSON expected LENGTH "${actions}" actions)
string(JSON count LENGTH "${results}" checkpoints)
if(NOT version EQUAL 1 OR NOT observed EQUAL expected OR count LESS 2)
    message(FATAL_ERROR "Incomplete native replay result inventory")
endif()
set(hashes "")
math(EXPR last "${count} - 1")
foreach(i RANGE 0 ${last})
    string(JSON label GET "${results}" checkpoints ${i} label)
    if(NOT label MATCHES "^[A-Za-z0-9_-]+$")
        message(FATAL_ERROR "Unsafe native checkpoint label")
    endif()
    foreach(extension sav world.json derived.json schema.json runtime.json)
        if(NOT EXISTS "${RUN_DIR}/${label}.${extension}")
            message(FATAL_ERROR "Missing native checkpoint ${label}.${extension}")
        endif()
        file(SIZE "${RUN_DIR}/${label}.${extension}" size)
        if(size EQUAL 0)
            message(FATAL_ERROR "Empty native checkpoint ${label}.${extension}")
        endif()
        file(SHA256 "${RUN_DIR}/${label}.${extension}" hash)
        string(APPEND hashes "${hash} ${label}.${extension}\n")
    endforeach()
    file(READ "${RUN_DIR}/${label}.world.json" world)
    string(JSON chunks LENGTH "${world}" chunks)
    string(JSON save_version GET "${world}" savegame_version)
    if(NOT chunks EQUAL 62 OR NOT save_version EQUAL 362)
        message(FATAL_ERROR "Incomplete native saved checkpoint ${label}")
    endif()
endforeach()
foreach(file actions.json results.json)
    file(SHA256 "${RUN_DIR}/${file}" hash)
    string(APPEND hashes "${hash} ${file}\n")
endforeach()
if(EXISTS "${RUN_DIR}/checkpoint-hashes.txt")
    file(READ "${RUN_DIR}/checkpoint-hashes.txt" recorded_hashes)
    if(NOT hashes STREQUAL recorded_hashes)
        message(FATAL_ERROR "Native evidence hashes changed after capture")
    endif()
else()
    file(WRITE "${RUN_DIR}/checkpoint-hashes.txt" "${hashes}")
endif()
message(STATUS "PASS native replay: ${observed} actions, ${count} complete checkpoints")
