cmake_minimum_required(VERSION 3.20)
foreach(required ORACLE RUN_DIR CONFIG INPUT REPLAY)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
get_filename_component(RUN_DIR "${RUN_DIR}" ABSOLUTE)
get_filename_component(INPUT "${INPUT}" ABSOLUTE)
get_filename_component(REPLAY "${REPLAY}" ABSOLUTE)
if(EXISTS "${RUN_DIR}")
    message(FATAL_ERROR "Replay run directory already exists (stale evidence): ${RUN_DIR}")
endif()
file(MAKE_DIRECTORY "${RUN_DIR}")
file(COPY_FILE "${CONFIG}" "${RUN_DIR}/openttd.cfg")
file(COPY_FILE "${REPLAY}" "${RUN_DIR}/actions.json")
file(SHA256 "${ORACLE}" oracle_hash)
file(SHA256 "${INPUT}" input_hash)
file(SHA256 "${REPLAY}" replay_hash)
file(WRITE "${RUN_DIR}/invocation.txt" "ORACLE=${ORACLE}\nORACLE_SHA256=${oracle_hash}\nINPUT=${INPUT}\nINPUT_SHA256=${input_hash}\nREPLAY=${REPLAY}\nREPLAY_SHA256=${replay_hash}\nCONFIG=${CONFIG}\nARGV=-X -x -c ${RUN_DIR}/openttd.cfg -vnull:ticks=8 -snull -mnull -g ${INPUT} -d sl=2\n")
get_filename_component(root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
file(GLOB patches RELATIVE "${root}" "${root}/reference/*.patch")
file(GLOB headers RELATIVE "${root}" "${root}/reference/*.hpp")
set(references ${patches} ${headers})
get_filename_component(build_directory "${ORACLE}" DIRECTORY)
if(NOT EXISTS "${build_directory}/replay-build.sha256")
    message(FATAL_ERROR "Missing native build freshness stamp; rerun setup-snapshot-reference.sh")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E sha256sum "${ORACLE}" ${references}
    WORKING_DIRECTORY "${root}" OUTPUT_VARIABLE current_stamp RESULT_VARIABLE stamp_result)
file(READ "${build_directory}/replay-build.sha256" built_stamp)
if(NOT stamp_result EQUAL 0 OR NOT current_stamp STREQUAL built_stamp)
    message(FATAL_ERROR "Stale native replay binary/source; rerun setup-snapshot-reference.sh")
endif()
foreach(reference IN LISTS references)
    file(SHA256 "${root}/${reference}" reference_hash)
    file(APPEND "${RUN_DIR}/invocation.txt" "SOURCE_SHA256=${reference_hash} ${reference}\n")
endforeach()
set(ENV{OTTD_REPLAY_PATH} "${REPLAY}")
set(ENV{OTTD_REPLAY_OUTPUT} "${RUN_DIR}")
execute_process(
    COMMAND "${ORACLE}" -X -x -c "${RUN_DIR}/openttd.cfg"
        -vnull:ticks=8 -snull -mnull -g "${INPUT}" -d sl=2
    WORKING_DIRECTORY "${RUN_DIR}"
    OUTPUT_FILE "${RUN_DIR}/stdout.log"
    ERROR_FILE "${RUN_DIR}/stderr.log"
    RESULT_VARIABLE result TIMEOUT 60)
file(WRITE "${RUN_DIR}/process.txt" "exit=${result}\n")
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Native replay failed (${result}); see ${RUN_DIR}/stderr.log")
endif()
file(READ "${RUN_DIR}/stderr.log" native_log)
if(native_log MATCHES "\\[(sl|grf):0\\]")
    message(FATAL_ERROR "Native replay reported a save/load/content error")
endif()
string(REGEX MATCHALL "Loading savegame version [0-9]+" loaded_versions "${native_log}")
list(LENGTH loaded_versions load_count)
if(NOT load_count EQUAL 2)
    message(FATAL_ERROR "Native replay loaded ${load_count} games; expected title plus requested input")
endif()
if(NOT EXISTS "${RUN_DIR}/results.json")
    message(FATAL_ERROR "Native replay did not emit results.json")
endif()
file(READ "${RUN_DIR}/results.json" results)
file(READ "${REPLAY}" actions)
string(JSON version GET "${results}" schema_version)
string(JSON observed LENGTH "${results}" actions)
string(JSON expected LENGTH "${actions}" actions)
string(JSON count LENGTH "${results}" checkpoints)
if(NOT version EQUAL 1 OR NOT observed EQUAL expected OR count LESS 2)
    message(FATAL_ERROR "Incomplete native replay result inventory")
endif()
math(EXPR last "${count} - 1")
foreach(i RANGE 0 ${last})
    string(JSON label GET "${results}" checkpoints ${i} label)
    foreach(extension sav world.json derived.json schema.json runtime.json)
        if(NOT EXISTS "${RUN_DIR}/${label}.${extension}")
            message(FATAL_ERROR "Missing native checkpoint ${label}.${extension}")
        endif()
        file(SIZE "${RUN_DIR}/${label}.${extension}" size)
        if(size EQUAL 0)
            message(FATAL_ERROR "Empty native checkpoint ${label}.${extension}")
        endif()
        file(SHA256 "${RUN_DIR}/${label}.${extension}" hash)
        file(APPEND "${RUN_DIR}/checkpoint-hashes.txt" "${hash} ${label}.${extension}\n")
    endforeach()
    file(READ "${RUN_DIR}/${label}.world.json" world)
    string(JSON chunks LENGTH "${world}" chunks)
    string(JSON save_version GET "${world}" savegame_version)
    if(NOT chunks EQUAL 62 OR NOT save_version EQUAL 362)
        message(FATAL_ERROR "Incomplete native saved checkpoint ${label}")
    endif()
endforeach()
message(STATUS "PASS native replay: ${observed} actions, ${count} complete checkpoints")
