cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED ORACLE)
    message(FATAL_ERROR "Missing ORACLE")
endif()
get_filename_component(root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
file(GLOB patches RELATIVE "${root}" "${root}/reference/*.patch")
file(GLOB headers RELATIVE "${root}" "${root}/reference/*.hpp")
set(references ${patches} ${headers})
get_filename_component(build_directory "${ORACLE}" DIRECTORY)
if(NOT EXISTS "${build_directory}/replay-build.sha256")
    message(FATAL_ERROR "Missing native build freshness stamp; rerun setup-snapshot-reference.sh")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E sha256sum "${ORACLE}" ${references}
    WORKING_DIRECTORY "${root}" OUTPUT_VARIABLE current_stamp RESULT_VARIABLE stamp_result)
file(READ "${build_directory}/replay-build.sha256" built_stamp)
if(NOT stamp_result EQUAL 0 OR NOT current_stamp STREQUAL built_stamp)
    message(FATAL_ERROR "Stale native replay binary/source; rerun setup-snapshot-reference.sh")
endif()
