cmake_minimum_required(VERSION 3.20)
foreach(required ORACLE RUN_DIR INPUT)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
get_filename_component(RUN_DIR "${RUN_DIR}" ABSOLUTE)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(EXISTS "${RUN_DIR}")
    message(FATAL_ERROR "Builder run directory must be fresh")
endif()
file(MAKE_DIRECTORY "${RUN_DIR}/ai" "${RUN_DIR}/scripts")
file(COPY "${ROOT}/fixtures/world/world-probe" DESTINATION "${RUN_DIR}/ai")
file(READ "${ROOT}/scripts/reference.cfg" config)
string(REPLACE "savegame_format = none" "savegame_format = zlib" config "${config}")
if(MODDED)
    file(MAKE_DIRECTORY "${RUN_DIR}/newgrf")
    file(COPY "${ROOT}/fixtures/content/contract-speed.grf" DESTINATION "${RUN_DIR}/newgrf")
    string(APPEND config "\n[newgrf]\ncontract-speed.grf = 123\n")
endif()
file(WRITE "${RUN_DIR}/fixture.cfg" "${config}")
file(WRITE "${RUN_DIR}/scripts/game_start.scr" "debug_level script=2,sl=2,desync=2\n")
if(NOT RELOAD)
    file(APPEND "${RUN_DIR}/scripts/game_start.scr" "start_ai WorldProbe\n")
endif()
set(CONFIG "${RUN_DIR}/fixture.cfg")
set(TICKS 2000)
include("${CMAKE_CURRENT_LIST_DIR}/check-world-reference.cmake")
file(READ "${RUN_DIR}/stderr.log" log)
if(RELOAD AND NOT log MATCHES "WORLD_RESTORED true")
    message(FATAL_ERROR "Native world builder did not restore its saved script state")
elseif(NOT RELOAD AND NOT log MATCHES "WORLD_READY first=[0-9]+ second=[0-9]+ hole=[0-9]+")
    message(FATAL_ERROR "Native world builder did not complete its checked commands")
endif()
if(MODDED AND NOT log MATCHES "WORLD_SPEED engine=0 speed=123")
    message(FATAL_ERROR "Native world builder did not observe the required GRF effect")
endif()
if(log MATCHES "\\[grf:0\\]")
    message(FATAL_ERROR "Native world builder reported content warnings")
endif()
message(STATUS "PASS native world builder commands")
