cmake_minimum_required(VERSION 3.20)
foreach(required ORACLE RUN_DIR CONFIG INPUT MANIFEST)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/check-replay-build.cmake")
foreach(variable OTTD_REPLAY_PATH OTTD_GRF_SAFETY_CASE OTTD_GRF_CONTROL_CASE)
    if(DEFINED ENV{${variable}})
        message(FATAL_ERROR "Dedicated full safety run forbids ${variable}")
    endif()
endforeach()
if(INPUT STREQUAL "GENERATE")
    message(FATAL_ERROR "Safety observer requires a saved game")
endif()
get_filename_component(RUN_DIR "${RUN_DIR}" ABSOLUTE)
if(EXISTS "${RUN_DIR}")
    message(FATAL_ERROR "Safety run directory already exists")
endif()
file(MAKE_DIRECTORY "${RUN_DIR}")
file(SHA256 "${ORACLE}" oracle_hash)
file(SHA256 "${MANIFEST}" manifest_hash)
file(SHA256 "${CONFIG}" config_hash)
file(SHA256 "${INPUT}" input_hash)
file(WRITE "${RUN_DIR}/invocation.txt" "ORACLE=${ORACLE}\nORACLE_SHA256=${oracle_hash}\nMANIFEST=${MANIFEST}\nMANIFEST_SHA256=${manifest_hash}\nINPUT=${INPUT}\nINPUT_SHA256=${input_hash}\nCONFIG_SHA256=${config_hash}\nUPSTREAM=14ec60f248547d4d062a1160f0fc26d742319888\nPHASE=original-FillGRFDetails-static-safety-after-load\n")
file(READ "${MANIFEST}" manifest)
string(JSON count LENGTH "${manifest}")
if(count LESS 1)
    message(FATAL_ERROR "Empty safety manifest")
endif()
math(EXPR last "${count} - 1")
foreach(index RANGE 0 ${last})
    string(JSON path GET "${manifest}" ${index} path)
    file(SHA256 "${path}" source_hash)
    file(APPEND "${RUN_DIR}/inputs.sha256" "${source_hash}  ${path}\n")
endforeach()
set(ENV{OTTD_GRF_SAFETY_INPUT} "${MANIFEST}")
set(ENV{OTTD_GRF_SAFETY_OUTPUT} "${RUN_DIR}/safety.json")
set(TICKS 1)
include("${CMAKE_CURRENT_LIST_DIR}/run-reference.cmake")
file(READ "${RUN_DIR}/safety.json" observation)
string(JSON observed_count LENGTH "${observation}" scans)
if(NOT observed_count EQUAL count)
    message(FATAL_ERROR "Safety observer did not consume every case")
endif()
message(STATUS "PASS original static safety observations: ${count}")
