cmake_minimum_required(VERSION 3.20)
foreach(required ORACLE RUN_DIR CONFIG INPUT MANIFEST)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/check-replay-build.cmake")
if(DEFINED ENV{OTTD_REPLAY_PATH} OR DEFINED ENV{OTTD_GRF_LANGUAGE_CASE})
    message(FATAL_ERROR "Language probe refuses replay or case subset")
endif()
get_filename_component(RUN_DIR "${RUN_DIR}" ABSOLUTE)
set(ENV{OTTD_GRF_LANGUAGE_OUTPUT} "${RUN_DIR}/language.json")
file(READ "${MANIFEST}" language_manifest)
string(JSON language_pack_count LENGTH "${language_manifest}" language pack_directories)
if(language_pack_count LESS 1 OR language_pack_count GREATER 256)
    message(FATAL_ERROR "Invalid language pack directory count")
endif()
set(language_pack_rows "")
math(EXPR language_last "${language_pack_count} - 1")
foreach(index RANGE 0 ${language_last})
    string(JSON pack_directory GET "${language_manifest}" language pack_directories ${index})
    file(GLOB pack_files "${pack_directory}/*")
    list(LENGTH pack_files pack_count)
    if(NOT pack_count EQUAL 1)
        message(FATAL_ERROR "Language directory must contain one pack")
    endif()
    list(GET pack_files 0 pack)
    file(SHA256 "${pack}" pack_hash)
    string(APPEND language_pack_rows "${pack_hash}  ${pack}\n")
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/check-grf-load-control-reference.cmake")
set(language_pack_after "")
foreach(index RANGE 0 ${language_last})
    string(JSON pack_directory GET "${language_manifest}" language pack_directories ${index})
    file(GLOB pack_files "${pack_directory}/*")
    list(LENGTH pack_files pack_count)
    if(NOT pack_count EQUAL 1)
        message(FATAL_ERROR "Language directory membership changed during native call")
    endif()
    list(GET pack_files 0 pack)
    file(SHA256 "${pack}" pack_hash)
    string(APPEND language_pack_after "${pack_hash}  ${pack}\n")
endforeach()
if(NOT language_pack_after STREQUAL language_pack_rows)
    message(FATAL_ERROR "Language source bytes changed during native call")
endif()
file(WRITE "${RUN_DIR}/language-inputs.sha256" "${language_pack_rows}")
file(READ "${RUN_DIR}/language.json" language_observation)
string(JSON phase GET "${language_observation}" phase)
if(NOT phase STREQUAL "actual-stage-major-language")
    message(FATAL_ERROR "Wrong language observation phase")
endif()
message(STATUS "PASS original language catalog/stage/text observation")
