cmake_minimum_required(VERSION 3.20)
foreach(required ORACLE RUN_DIR CONFIG INPUT MANIFEST)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/check-replay-build.cmake")
if(DEFINED ENV{OTTD_REPLAY_PATH} OR DEFINED ENV{OTTD_GRF_STRINGS_CASE})
    message(FATAL_ERROR "String API probe refuses replay or case subset")
endif()
get_filename_component(RUN_DIR "${RUN_DIR}" ABSOLUTE)
set(ENV{OTTD_GRF_STRINGS_OUTPUT} "${RUN_DIR}/strings.json")
include("${CMAKE_CURRENT_LIST_DIR}/check-grf-language-reference.cmake")
file(READ "${RUN_DIR}/strings.json" observation)
string(JSON mode GET "${observation}" mode)
string(JSON arms GET "${observation}" arms)
string(JSON consumptions GET "${observation}" consumptions)
file(READ "${MANIFEST}" strings_manifest)
string(JSON load_mode ERROR_VARIABLE absent GET "${strings_manifest}" strings_load)
if(absent)
    set(expected_mode "separate-process-original-string-api")
else()
    set(expected_mode "actual-stage-major-custom-strings")
endif()
if(NOT mode STREQUAL expected_mode OR NOT arms EQUAL 1 OR NOT consumptions EQUAL 1)
    message(FATAL_ERROR "Wrong original string API invocation")
endif()
message(STATUS "PASS original strings witness: ${mode}, with original load/save completion")
