cmake_minimum_required(VERSION 3.20)
foreach(required ORACLE RUN_DIR CONFIG INPUT)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
if(DEFINED ENV{OTTD_REPLAY_PATH})
    message(FATAL_ERROR "Allocation observer requires a dedicated invocation")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/check-replay-build.cmake")
get_filename_component(RUN_DIR "${RUN_DIR}" ABSOLUTE)
if(EXISTS "${RUN_DIR}")
    message(FATAL_ERROR "Allocation run directory already exists: ${RUN_DIR}")
endif()
file(MAKE_DIRECTORY "${RUN_DIR}")
file(SHA256 "${ORACLE}" oracle_hash)
file(SHA256 "${INPUT}" input_hash)
file(SHA256 "${CONFIG}" config_hash)
file(WRITE "${RUN_DIR}/invocation.txt" "ORACLE=${ORACLE}\nORACLE_SHA256=${oracle_hash}\nINPUT=${INPUT}\nINPUT_SHA256=${input_hash}\nCONFIG_SHA256=${config_hash}\nUPSTREAM=14ec60f248547d4d062a1160f0fc26d742319888\nPHASE=scratch-original-pool-and-unit-generators\n")
set(ENV{OTTD_ALLOCATION_PROBES_PATH} "${RUN_DIR}/allocation.json")
set(TICKS 1)
include("${CMAKE_CURRENT_LIST_DIR}/run-reference.cmake")
file(READ "${RUN_DIR}/allocation.json" result)
string(JSON schema GET "${result}" schema_version)
string(JSON pools LENGTH "${result}" pools)
string(JSON units LENGTH "${result}" units)
if(NOT schema EQUAL 1 OR NOT pools EQUAL 2 OR units LESS 10)
    message(FATAL_ERROR "Incomplete allocation trace")
endif()
message(STATUS "PASS native allocation traces: ${pools} pools, ${units} unit operations")
