cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED RUN_DIR)
    message(FATAL_ERROR "Missing RUN_DIR")
endif()
get_filename_component(RUN_DIR "${RUN_DIR}" ABSOLUTE)
if(EXISTS "${RUN_DIR}/snapshot.json" OR EXISTS "${RUN_DIR}/primitives.json")
    message(FATAL_ERROR "Run directory contains stale oracle output: ${RUN_DIR}")
endif()
set(ENV{OTTD_SNAPSHOT_PATH} "${RUN_DIR}/snapshot.json")
set(ENV{OTTD_PRIMITIVES_PATH} "${RUN_DIR}/primitives.json")
include("${CMAKE_CURRENT_LIST_DIR}/run-reference.cmake")
foreach(artifact snapshot.json primitives.json)
    if(NOT EXISTS "${RUN_DIR}/${artifact}")
        message(FATAL_ERROR "Reference engine did not emit ${artifact}")
    endif()
    file(SIZE "${RUN_DIR}/${artifact}" size)
    if(size EQUAL 0)
        message(FATAL_ERROR "Reference engine emitted empty ${artifact}")
    endif()
endforeach()
