cmake_minimum_required(VERSION 3.20)
foreach(required ORACLE RUN_DIR CONFIG INPUT)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/check-replay-build.cmake")
get_filename_component(RUN_DIR "${RUN_DIR}" ABSOLUTE)
if(EXISTS "${RUN_DIR}")
    message(FATAL_ERROR "Terrain run directory already exists: ${RUN_DIR}")
endif()
file(MAKE_DIRECTORY "${RUN_DIR}")
file(SHA256 "${ORACLE}" oracle_hash)
file(SHA256 "${INPUT}" input_hash)
file(SHA256 "${CONFIG}" config_hash)
file(WRITE "${RUN_DIR}/invocation.txt" "ORACLE=${ORACLE}\nORACLE_SHA256=${oracle_hash}\nINPUT=${INPUT}\nINPUT_SHA256=${input_hash}\nCONFIG=${CONFIG}\nCONFIG_SHA256=${config_hash}\nUPSTREAM=14ec60f248547d4d062a1160f0fc26d742319888\nPHASE=after-load\n")
set(ENV{OTTD_TERRAIN_PROBES_PATH} "${RUN_DIR}/terrain.json")
set(TICKS 1)
include("${CMAKE_CURRENT_LIST_DIR}/run-reference.cmake")
file(READ "${RUN_DIR}/terrain.json" vectors)
string(JSON schema GET "${vectors}" schema_version)
string(JSON slopes LENGTH "${vectors}" slopes)
string(JSON foundations LENGTH "${vectors}" foundations)
string(JSON width GET "${vectors}" map width)
string(JSON height GET "${vectors}" map height)
string(JSON tiles LENGTH "${vectors}" map tiles)
math(EXPR expected_tiles "${width} * ${height}")
if(NOT schema EQUAL 1 OR NOT slopes EQUAL 100 OR NOT foundations EQUAL 232 OR NOT tiles EQUAL expected_tiles)
    message(FATAL_ERROR "Incomplete terrain observation")
endif()
string(JSON altered SET "${vectors}" slopes 0 pixels 0 1)
file(WRITE "${RUN_DIR}/negative.json" "${altered}\n")
message(STATUS "PASS native terrain observation: ${slopes} slopes, ${foundations} foundations, ${tiles} tiles")
