# SPDX-License-Identifier: GPL-2.0-only
"""Actual-native comment/switch budget stages and independently observed controls."""

SWITCH_BUDGETS = (
    ("switch_000.nut", (0,), "suspend"),
    ("switch_000.nut", (1,), "suspend"),
    ("switch_000.nut", (2,), "suspend"),
    ("switch_000.nut", (3,), "return"),
    ("switch_000.nut", (2, 2, 2, 2), "return"),
    ("switch_005.nut", (0,), "suspend"),
    ("switch_005.nut", (1,), "suspend"),
    ("switch_005.nut", (2,), "return"),
    ("switch_005.nut", (2, 2, 2), "return"),
    ("switch_013.nut", (0,), "suspend"),
    ("switch_013.nut", (1,), "suspend"),
    ("switch_013.nut", (2,), "suspend"),
    ("switch_013.nut", (5,), "suspend"),
    ("switch_013.nut", (6,), "suspend"),
    ("switch_013.nut", (7,), "return"),
    ("switch_013.nut", (2, 2, 2, 2, 2, 2, 2, 2), "return"),
    ("switch_015.nut", (0,), "suspend"),
    ("switch_015.nut", (1,), "suspend"),
    ("switch_015.nut", (2,), "suspend"),
    ("switch_015.nut", (8,), "suspend"),
    ("switch_015.nut", (9,), "suspend"),
    ("switch_015.nut", (10,), "return"),
    ("switch_015.nut", (2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2), "return"),
    ("switch_091.nut", (0,), "suspend"),
    ("switch_091.nut", (1,), "suspend"),
    ("switch_091.nut", (2,), "suspend"),
    ("switch_091.nut", (50,), "suspend"),
    ("switch_091.nut", (51,), "suspend"),
    ("switch_091.nut", (52,), "return"),
    (
        "switch_091.nut",
        (
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
        ),
        "return",
    ),
    ("switch_092.nut", (0,), "suspend"),
    ("switch_092.nut", (1,), "suspend"),
    ("switch_092.nut", (2,), "suspend"),
    ("switch_092.nut", (33,), "suspend"),
    ("switch_092.nut", (34,), "suspend"),
    ("switch_092.nut", (35,), "return"),
    (
        "switch_092.nut",
        (
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
        ),
        "return",
    ),
    ("branch_switch_case_frame.nut", (0,), "suspend"),
    ("branch_switch_case_frame.nut", (1,), "suspend"),
    ("branch_switch_case_frame.nut", (2,), "suspend"),
    ("branch_switch_case_frame.nut", (9,), "suspend"),
    ("branch_switch_case_frame.nut", (10,), "suspend"),
    ("branch_switch_case_frame.nut", (11,), "return"),
    ("branch_switch_case_frame.nut", (2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2), "return"),
    ("branch_switch_continue_frame.nut", (0,), "suspend"),
    ("branch_switch_continue_frame.nut", (1,), "suspend"),
    ("branch_switch_continue_frame.nut", (2,), "suspend"),
    ("branch_switch_continue_frame.nut", (46,), "suspend"),
    ("branch_switch_continue_frame.nut", (47,), "suspend"),
    ("branch_switch_continue_frame.nut", (48,), "return"),
    (
        "branch_switch_continue_frame.nut",
        (
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
        ),
        "return",
    ),
)

SWITCH_CONTROLS = {
    "switch-block-newline": (
        "switch_000.nut",
        "return 9998 integer 1",
        "return 9998 null",
    ),
    "switch-line-newline": (
        "switch_005.nut",
        "return 9999 null",
        "return 9999 integer 1",
    ),
    "switch-selector-alias": (
        "switch_013.nut",
        "return 9994 bool 1",
        "return 9994 integer 9",
    ),
    "switch-fallthrough": (
        "switch_015.nut",
        "return 9991 integer 2",
        "return 9991 integer 9",
    ),
    "switch-case-destination": (
        "branch_switch_case_frame.nut",
        "op 15 2 2 1 0",
        "op 15 3 2 1 0",
    ),
    "switch-continue-target": (
        "branch_switch_continue_frame.nut",
        "op 24 0 -20 0 0",
        "op 24 0 20 0 0",
    ),
}
