# SPDX-License-Identifier: GPL-2.0-only
"""Frozen actual-native iteration budget stages and corruption witnesses."""

ITERATION_BUDGETS = (
    ("iteration_016.nut", (0,), "suspend"),
    ("iteration_016.nut", (1,), "suspend"),
    ("iteration_016.nut", (2,), "suspend"),
    ("iteration_016.nut", (33,), "suspend"),
    ("iteration_016.nut", (34,), "suspend"),
    ("iteration_016.nut", (35,), "return"),
    ("iteration_016.nut", (2,) * 37, "return"),
    ("iteration_013.nut", (0,), "suspend"),
    ("iteration_013.nut", (1,), "suspend"),
    ("iteration_013.nut", (2,), "suspend"),
    ("iteration_013.nut", (45,), "suspend"),
    ("iteration_013.nut", (46,), "suspend"),
    ("iteration_013.nut", (47,), "return"),
    ("iteration_013.nut", (2,) * 49, "return"),
    ("iteration_010.nut", (0,), "suspend"),
    ("iteration_010.nut", (1,), "suspend"),
    ("iteration_010.nut", (2,), "suspend"),
    ("iteration_010.nut", (32,), "suspend"),
    ("iteration_010.nut", (33,), "suspend"),
    ("iteration_010.nut", (34,), "return"),
    ("iteration_010.nut", (2,) * 36, "return"),
    ("iteration_024.nut", (0,), "suspend"),
    ("iteration_024.nut", (1,), "suspend"),
    ("iteration_024.nut", (2,), "suspend"),
    ("iteration_024.nut", (3,), "suspend"),
    ("iteration_024.nut", (4,), "suspend"),
    ("iteration_024.nut", (5,), "return"),
    ("iteration_024.nut", (2,) * 7, "return"),
    ("iteration_021.nut", (0,), "suspend"),
    ("iteration_021.nut", (1,), "suspend"),
    ("iteration_021.nut", (2,), "suspend"),
    ("iteration_021.nut", (3,), "suspend"),
    ("iteration_021.nut", (4,), "suspend"),
    ("iteration_021.nut", (5,), "return"),
    ("iteration_021.nut", (2,) * 7, "return"),
    ("iteration_036.nut", (0,), "suspend"),
    ("iteration_036.nut", (1,), "suspend"),
    ("iteration_036.nut", (2,), "suspend"),
    ("iteration_036.nut", (8,), "suspend"),
    ("iteration_036.nut", (9,), "suspend"),
    ("iteration_036.nut", (10,), "return"),
    ("iteration_036.nut", (2,) * 12, "return"),
    ("branch_iteration_update_frame.nut", (0,), "suspend"),
    ("branch_iteration_update_frame.nut", (1,), "suspend"),
    ("branch_iteration_update_frame.nut", (2,), "suspend"),
    ("branch_iteration_update_frame.nut", (15,), "suspend"),
    ("branch_iteration_update_frame.nut", (16,), "suspend"),
    ("branch_iteration_update_frame.nut", (17,), "return"),
    ("branch_iteration_update_frame.nut", (2,) * 19, "return"),
    ("branch_iteration_loop_frame.nut", (0,), "suspend"),
    ("branch_iteration_loop_frame.nut", (1,), "suspend"),
    ("branch_iteration_loop_frame.nut", (2,), "suspend"),
    ("branch_iteration_loop_frame.nut", (35,), "suspend"),
    ("branch_iteration_loop_frame.nut", (36,), "suspend"),
    ("branch_iteration_loop_frame.nut", (37,), "return"),
    ("branch_iteration_loop_frame.nut", (2,) * 39, "return"),
    ("iteration_015.nut", (0,), "suspend"),
    ("iteration_015.nut", (1,), "suspend"),
    ("iteration_015.nut", (2,) * 25, "suspend"),
    ("iteration_015.nut", (10000,), "suspend"),
)

ITERATION_CONTROLS = {
    "iteration-shift": ("iteration_029.nut", "op 18 1 2 1 6", "op 18 1 2 1 5"),
    "iteration-postfix": ("iteration_021.nut", "op 39 2 1 0 1", "op 37 2 1 0 1"),
    "iteration-do": ("iteration_011.nut", "op 25 2 -4 0 0", "op 26 2 -4 0 0"),
    "iteration-relocation": ("iteration_015.nut", "op 17 1 3 1 43", "op 17 2 3 1 43"),
    "iteration-ternary": (
        "iteration_035.nut",
        "return 9995 integer 7",
        "runtime_error 9995",
    ),
}
