// SPDX-License-Identifier: GPL-2.0-only
// OpenTTD 14ec60f: currency.cpp origin_currency_specs; named StringIDs from its strgen output.
use super::load_currency::CurrencyDefault;
pub(super) const DEFAULTS: [CurrencyDefault; 46] = [
    CurrencyDefault {
        rate: 1,
        separator: "",
        to_euro: 0,
        prefix: "£",
        suffix: "",
        code: "GBP",
        symbol_pos: 0,
        name: 808,
    },
    CurrencyDefault {
        rate: 2,
        separator: "",
        to_euro: 0,
        prefix: "$",
        suffix: "",
        code: "USD",
        symbol_pos: 0,
        name: 809,
    },
    CurrencyDefault {
        rate: 2,
        separator: "",
        to_euro: 1,
        prefix: "€",
        suffix: "",
        code: "EUR",
        symbol_pos: 0,
        name: 810,
    },
    CurrencyDefault {
        rate: 220,
        separator: "",
        to_euro: 0,
        prefix: "¥",
        suffix: "",
        code: "JPY",
        symbol_pos: 0,
        name: 811,
    },
    CurrencyDefault {
        rate: 27,
        separator: "",
        to_euro: 2002,
        prefix: "",
        suffix: " S.",
        code: "ATS",
        symbol_pos: 1,
        name: 812,
    },
    CurrencyDefault {
        rate: 81,
        separator: "",
        to_euro: 2002,
        prefix: "BEF ",
        suffix: "",
        code: "BEF",
        symbol_pos: 0,
        name: 813,
    },
    CurrencyDefault {
        rate: 2,
        separator: "",
        to_euro: 0,
        prefix: "CHF ",
        suffix: "",
        code: "CHF",
        symbol_pos: 0,
        name: 814,
    },
    CurrencyDefault {
        rate: 41,
        separator: "",
        to_euro: 0,
        prefix: "",
        suffix: " Kč",
        code: "CZK",
        symbol_pos: 1,
        name: 815,
    },
    CurrencyDefault {
        rate: 4,
        separator: "",
        to_euro: 2002,
        prefix: "DM ",
        suffix: "",
        code: "DEM",
        symbol_pos: 0,
        name: 816,
    },
    CurrencyDefault {
        rate: 11,
        separator: "",
        to_euro: 0,
        prefix: "",
        suffix: " kr",
        code: "DKK",
        symbol_pos: 1,
        name: 817,
    },
    CurrencyDefault {
        rate: 333,
        separator: "",
        to_euro: 2002,
        prefix: "Pts ",
        suffix: "",
        code: "ESP",
        symbol_pos: 0,
        name: 818,
    },
    CurrencyDefault {
        rate: 12,
        separator: "",
        to_euro: 2002,
        prefix: "",
        suffix: " mk",
        code: "FIM",
        symbol_pos: 1,
        name: 819,
    },
    CurrencyDefault {
        rate: 13,
        separator: "",
        to_euro: 2002,
        prefix: "FF ",
        suffix: "",
        code: "FRF",
        symbol_pos: 0,
        name: 820,
    },
    CurrencyDefault {
        rate: 681,
        separator: "",
        to_euro: 2002,
        prefix: "",
        suffix: "Dr.",
        code: "GRD",
        symbol_pos: 1,
        name: 821,
    },
    CurrencyDefault {
        rate: 378,
        separator: "",
        to_euro: 0,
        prefix: "",
        suffix: " Ft",
        code: "HUF",
        symbol_pos: 1,
        name: 822,
    },
    CurrencyDefault {
        rate: 130,
        separator: "",
        to_euro: 0,
        prefix: "",
        suffix: " Kr",
        code: "ISK",
        symbol_pos: 1,
        name: 823,
    },
    CurrencyDefault {
        rate: 3873,
        separator: "",
        to_euro: 2002,
        prefix: "",
        suffix: " L.",
        code: "ITL",
        symbol_pos: 1,
        name: 824,
    },
    CurrencyDefault {
        rate: 4,
        separator: "",
        to_euro: 2002,
        prefix: "NLG ",
        suffix: "",
        code: "NLG",
        symbol_pos: 0,
        name: 825,
    },
    CurrencyDefault {
        rate: 12,
        separator: "",
        to_euro: 0,
        prefix: "",
        suffix: " Kr",
        code: "NOK",
        symbol_pos: 1,
        name: 826,
    },
    CurrencyDefault {
        rate: 6,
        separator: "",
        to_euro: 0,
        prefix: "",
        suffix: " zł",
        code: "PLN",
        symbol_pos: 1,
        name: 827,
    },
    CurrencyDefault {
        rate: 5,
        separator: "",
        to_euro: 0,
        prefix: "",
        suffix: " Lei",
        code: "RON",
        symbol_pos: 1,
        name: 828,
    },
    CurrencyDefault {
        rate: 50,
        separator: "",
        to_euro: 0,
        prefix: "",
        suffix: " p",
        code: "RUR",
        symbol_pos: 1,
        name: 829,
    },
    CurrencyDefault {
        rate: 479,
        separator: "",
        to_euro: 2007,
        prefix: "",
        suffix: " SIT",
        code: "SIT",
        symbol_pos: 1,
        name: 830,
    },
    CurrencyDefault {
        rate: 13,
        separator: "",
        to_euro: 0,
        prefix: "",
        suffix: " Kr",
        code: "SEK",
        symbol_pos: 1,
        name: 831,
    },
    CurrencyDefault {
        rate: 3,
        separator: "",
        to_euro: 0,
        prefix: "",
        suffix: " TL",
        code: "TRY",
        symbol_pos: 1,
        name: 832,
    },
    CurrencyDefault {
        rate: 60,
        separator: "",
        to_euro: 2009,
        prefix: "",
        suffix: " Sk",
        code: "SKK",
        symbol_pos: 1,
        name: 833,
    },
    CurrencyDefault {
        rate: 4,
        separator: "",
        to_euro: 0,
        prefix: "R$ ",
        suffix: "",
        code: "BRL",
        symbol_pos: 0,
        name: 834,
    },
    CurrencyDefault {
        rate: 31,
        separator: "",
        to_euro: 2011,
        prefix: "",
        suffix: " EEK",
        code: "EEK",
        symbol_pos: 1,
        name: 835,
    },
    CurrencyDefault {
        rate: 4,
        separator: "",
        to_euro: 2015,
        prefix: "",
        suffix: " Lt",
        code: "LTL",
        symbol_pos: 1,
        name: 836,
    },
    CurrencyDefault {
        rate: 1850,
        separator: "",
        to_euro: 0,
        prefix: "₩",
        suffix: "",
        code: "KRW",
        symbol_pos: 0,
        name: 837,
    },
    CurrencyDefault {
        rate: 13,
        separator: "",
        to_euro: 0,
        prefix: "R ",
        suffix: "",
        code: "ZAR",
        symbol_pos: 0,
        name: 838,
    },
    CurrencyDefault {
        rate: 1,
        separator: "",
        to_euro: 0,
        prefix: "",
        suffix: "",
        code: "",
        symbol_pos: 2,
        name: 839,
    },
    CurrencyDefault {
        rate: 3,
        separator: "",
        to_euro: 0,
        prefix: "",
        suffix: " GEL",
        code: "GEL",
        symbol_pos: 1,
        name: 840,
    },
    CurrencyDefault {
        rate: 4901,
        separator: "",
        to_euro: 0,
        prefix: "",
        suffix: " Rls",
        code: "IRR",
        symbol_pos: 1,
        name: 841,
    },
    CurrencyDefault {
        rate: 80,
        separator: "",
        to_euro: 0,
        prefix: "",
        suffix: " rub",
        code: "RUB",
        symbol_pos: 1,
        name: 842,
    },
    CurrencyDefault {
        rate: 24,
        separator: "",
        to_euro: 0,
        prefix: "$",
        suffix: "",
        code: "MXN",
        symbol_pos: 0,
        name: 843,
    },
    CurrencyDefault {
        rate: 40,
        separator: "",
        to_euro: 0,
        prefix: "NTD ",
        suffix: "",
        code: "NTD",
        symbol_pos: 0,
        name: 844,
    },
    CurrencyDefault {
        rate: 8,
        separator: "",
        to_euro: 0,
        prefix: "¥",
        suffix: "",
        code: "CNY",
        symbol_pos: 0,
        name: 845,
    },
    CurrencyDefault {
        rate: 10,
        separator: "",
        to_euro: 0,
        prefix: "HKD ",
        suffix: "",
        code: "HKD",
        symbol_pos: 0,
        name: 846,
    },
    CurrencyDefault {
        rate: 90,
        separator: "",
        to_euro: 0,
        prefix: "₹",
        suffix: "",
        code: "INR",
        symbol_pos: 0,
        name: 847,
    },
    CurrencyDefault {
        rate: 19,
        separator: "",
        to_euro: 0,
        prefix: "Rp",
        suffix: "",
        code: "IDR",
        symbol_pos: 0,
        name: 848,
    },
    CurrencyDefault {
        rate: 5,
        separator: "",
        to_euro: 0,
        prefix: "RM",
        suffix: "",
        code: "MYR",
        symbol_pos: 0,
        name: 849,
    },
    CurrencyDefault {
        rate: 1,
        separator: "",
        to_euro: 2014,
        prefix: "",
        suffix: " Ls",
        code: "LVL",
        symbol_pos: 1,
        name: 850,
    },
    CurrencyDefault {
        rate: 400,
        separator: "",
        to_euro: 2002,
        prefix: "",
        suffix: "$00",
        code: "PTE",
        symbol_pos: 1,
        name: 851,
    },
    CurrencyDefault {
        rate: 50,
        separator: "",
        to_euro: 0,
        prefix: "",
        suffix: " ₴",
        code: "UAH",
        symbol_pos: 1,
        name: 852,
    },
    CurrencyDefault {
        rate: 35000,
        separator: "",
        to_euro: 0,
        prefix: "",
        suffix: " ₫",
        code: "VND",
        symbol_pos: 1,
        name: 853,
    },
];
