// SPDX-License-Identifier: GPL-2.0-only
// Ported from OpenTTD 14ec60f248547d4d062a1160f0fc26d742319888 src/table/engines.h.
use super::AircraftSpec;
pub(super) const VEHICLES: [AircraftSpec; 41] = [
    AircraftSpec {
        image_index: 1,
        cost_factor: 14,
        running_cost: 85,
        subtype: 1,
        sfx: 6,
        acceleration: 18,
        max_speed: 473,
        mail_capacity: 4,
        passenger_capacity: 25,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 0,
        cost_factor: 15,
        running_cost: 100,
        subtype: 1,
        sfx: 6,
        acceleration: 20,
        max_speed: 473,
        mail_capacity: 8,
        passenger_capacity: 65,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 2,
        cost_factor: 16,
        running_cost: 130,
        subtype: 3,
        sfx: 7,
        acceleration: 35,
        max_speed: 947,
        mail_capacity: 10,
        passenger_capacity: 90,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 8,
        cost_factor: 75,
        running_cost: 250,
        subtype: 3,
        sfx: 59,
        acceleration: 50,
        max_speed: 2316,
        mail_capacity: 20,
        passenger_capacity: 100,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 5,
        cost_factor: 15,
        running_cost: 98,
        subtype: 1,
        sfx: 6,
        acceleration: 20,
        max_speed: 473,
        mail_capacity: 6,
        passenger_capacity: 30,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 6,
        cost_factor: 18,
        running_cost: 240,
        subtype: 3,
        sfx: 7,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 30,
        passenger_capacity: 200,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 2,
        cost_factor: 17,
        running_cost: 150,
        subtype: 1,
        sfx: 7,
        acceleration: 35,
        max_speed: 947,
        mail_capacity: 15,
        passenger_capacity: 100,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 2,
        cost_factor: 18,
        running_cost: 245,
        subtype: 3,
        sfx: 7,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 30,
        passenger_capacity: 150,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 3,
        cost_factor: 19,
        running_cost: 192,
        subtype: 3,
        sfx: 7,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 40,
        passenger_capacity: 220,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 3,
        cost_factor: 20,
        running_cost: 190,
        subtype: 3,
        sfx: 7,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 25,
        passenger_capacity: 230,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 2,
        cost_factor: 16,
        running_cost: 135,
        subtype: 3,
        sfx: 7,
        acceleration: 35,
        max_speed: 947,
        mail_capacity: 10,
        passenger_capacity: 95,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 2,
        cost_factor: 18,
        running_cost: 240,
        subtype: 3,
        sfx: 7,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 35,
        passenger_capacity: 170,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 4,
        cost_factor: 17,
        running_cost: 155,
        subtype: 3,
        sfx: 7,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 15,
        passenger_capacity: 110,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 7,
        cost_factor: 30,
        running_cost: 253,
        subtype: 3,
        sfx: 61,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 50,
        passenger_capacity: 300,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 4,
        cost_factor: 18,
        running_cost: 210,
        subtype: 3,
        sfx: 7,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 25,
        passenger_capacity: 200,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 4,
        cost_factor: 19,
        running_cost: 220,
        subtype: 3,
        sfx: 7,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 25,
        passenger_capacity: 240,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 4,
        cost_factor: 27,
        running_cost: 230,
        subtype: 3,
        sfx: 7,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 40,
        passenger_capacity: 260,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 3,
        cost_factor: 25,
        running_cost: 225,
        subtype: 3,
        sfx: 7,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 35,
        passenger_capacity: 240,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 4,
        cost_factor: 20,
        running_cost: 235,
        subtype: 3,
        sfx: 7,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 30,
        passenger_capacity: 260,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 4,
        cost_factor: 19,
        running_cost: 220,
        subtype: 3,
        sfx: 7,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 25,
        passenger_capacity: 210,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 4,
        cost_factor: 18,
        running_cost: 170,
        subtype: 3,
        sfx: 7,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 20,
        passenger_capacity: 160,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 4,
        cost_factor: 26,
        running_cost: 210,
        subtype: 3,
        sfx: 7,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 20,
        passenger_capacity: 220,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 6,
        cost_factor: 16,
        running_cost: 125,
        subtype: 1,
        sfx: 7,
        acceleration: 50,
        max_speed: 947,
        mail_capacity: 10,
        passenger_capacity: 80,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 2,
        cost_factor: 17,
        running_cost: 145,
        subtype: 1,
        sfx: 7,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 10,
        passenger_capacity: 85,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 11,
        cost_factor: 16,
        running_cost: 130,
        subtype: 1,
        sfx: 7,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 10,
        passenger_capacity: 75,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 10,
        cost_factor: 16,
        running_cost: 149,
        subtype: 1,
        sfx: 7,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 10,
        passenger_capacity: 85,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 15,
        cost_factor: 17,
        running_cost: 170,
        subtype: 1,
        sfx: 7,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 18,
        passenger_capacity: 65,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 12,
        cost_factor: 18,
        running_cost: 210,
        subtype: 3,
        sfx: 7,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 25,
        passenger_capacity: 110,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 13,
        cost_factor: 20,
        running_cost: 230,
        subtype: 3,
        sfx: 7,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 60,
        passenger_capacity: 180,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 14,
        cost_factor: 21,
        running_cost: 220,
        subtype: 3,
        sfx: 7,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 65,
        passenger_capacity: 150,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 16,
        cost_factor: 19,
        running_cost: 160,
        subtype: 3,
        sfx: 7,
        acceleration: 40,
        max_speed: 2316,
        mail_capacity: 45,
        passenger_capacity: 85,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 17,
        cost_factor: 24,
        running_cost: 248,
        subtype: 3,
        sfx: 61,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 80,
        passenger_capacity: 400,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 18,
        cost_factor: 80,
        running_cost: 251,
        subtype: 3,
        sfx: 59,
        acceleration: 50,
        max_speed: 2316,
        mail_capacity: 45,
        passenger_capacity: 130,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 20,
        cost_factor: 13,
        running_cost: 85,
        subtype: 1,
        sfx: 69,
        acceleration: 18,
        max_speed: 473,
        mail_capacity: 5,
        passenger_capacity: 25,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 21,
        cost_factor: 18,
        running_cost: 100,
        subtype: 1,
        sfx: 70,
        acceleration: 20,
        max_speed: 473,
        mail_capacity: 9,
        passenger_capacity: 60,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 22,
        cost_factor: 25,
        running_cost: 140,
        subtype: 1,
        sfx: 7,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 12,
        passenger_capacity: 90,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 23,
        cost_factor: 32,
        running_cost: 220,
        subtype: 3,
        sfx: 61,
        acceleration: 40,
        max_speed: 947,
        mail_capacity: 40,
        passenger_capacity: 200,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 24,
        cost_factor: 80,
        running_cost: 255,
        subtype: 3,
        sfx: 59,
        acceleration: 50,
        max_speed: 2316,
        mail_capacity: 30,
        passenger_capacity: 100,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 9,
        cost_factor: 15,
        running_cost: 81,
        subtype: 0,
        sfx: 7,
        acceleration: 20,
        max_speed: 320,
        mail_capacity: 15,
        passenger_capacity: 40,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 19,
        cost_factor: 17,
        running_cost: 77,
        subtype: 0,
        sfx: 7,
        acceleration: 20,
        max_speed: 512,
        mail_capacity: 20,
        passenger_capacity: 55,
        ..AircraftSpec::DEFAULT
    },
    AircraftSpec {
        image_index: 25,
        cost_factor: 15,
        running_cost: 80,
        subtype: 0,
        sfx: 7,
        acceleration: 20,
        max_speed: 320,
        mail_capacity: 10,
        passenger_capacity: 40,
        ..AircraftSpec::DEFAULT
    },
];
