// SPDX-License-Identifier: GPL-2.0-only
// Ported from OpenTTD 14ec60f248547d4d062a1160f0fc26d742319888 src/table/cargo_const.h.
use super::CargoSpec;
pub(super) const CARGO: [CargoSpec; 35] = [
    CargoSpec {
        label: 1_346_458_451,
        bitnum: 0,
        legend_colour: 152,
        rating_colour: 152,
        weight: 1,
        multiplier: 0x400,
        classes: 1,
        initial_payment: 3185,
        transit_periods: [0, 24],
        is_freight: false,
        town_acceptance_effect: 1,
        town_production_effect: 1,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_129_267_532,
        bitnum: 1,
        legend_colour: 6,
        rating_colour: 6,
        weight: 16,
        multiplier: 0x100,
        classes: 16_400,
        initial_payment: 5916,
        transit_periods: [7, 255],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_296_124_236,
        bitnum: 2,
        legend_colour: 15,
        rating_colour: 15,
        weight: 4,
        multiplier: 0x200,
        classes: 2,
        initial_payment: 4550,
        transit_periods: [20, 90],
        is_freight: false,
        town_acceptance_effect: 2,
        town_production_effect: 2,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_330_203_743,
        bitnum: 3,
        legend_colour: 174,
        rating_colour: 174,
        weight: 16,
        multiplier: 0x100,
        classes: 16_448,
        initial_payment: 4437,
        transit_periods: [25, 255],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_330_203_743,
        bitnum: 3,
        legend_colour: 174,
        rating_colour: 174,
        weight: 16,
        multiplier: 0x100,
        classes: 16_448,
        initial_payment: 4892,
        transit_periods: [25, 255],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_280_725_844,
        bitnum: 4,
        legend_colour: 208,
        rating_colour: 208,
        weight: 3,
        multiplier: 0x100,
        classes: 16_416,
        initial_payment: 4322,
        transit_periods: [4, 18],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_196_379_972,
        bitnum: 5,
        legend_colour: 194,
        rating_colour: 194,
        weight: 8,
        multiplier: 0x200,
        classes: 4,
        initial_payment: 6144,
        transit_periods: [5, 28],
        is_freight: true,
        town_acceptance_effect: 3,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_196_573_001,
        bitnum: 6,
        legend_colour: 191,
        rating_colour: 191,
        weight: 16,
        multiplier: 0x100,
        classes: 8208,
        initial_payment: 4778,
        transit_periods: [4, 40],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_464_354_113,
        bitnum: 6,
        legend_colour: 191,
        rating_colour: 191,
        weight: 16,
        multiplier: 0x100,
        classes: 8208,
        initial_payment: 4778,
        transit_periods: [4, 40],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_296_124_250,
        bitnum: 6,
        legend_colour: 191,
        rating_colour: 191,
        weight: 16,
        multiplier: 0x100,
        classes: 8208,
        initial_payment: 4322,
        transit_periods: [4, 40],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_464_815_428,
        bitnum: 7,
        legend_colour: 84,
        rating_colour: 84,
        weight: 16,
        multiplier: 0x100,
        classes: 32,
        initial_payment: 5005,
        transit_periods: [15, 255],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_464_815_428,
        bitnum: 7,
        legend_colour: 84,
        rating_colour: 84,
        weight: 16,
        multiplier: 0x100,
        classes: 32,
        initial_payment: 7964,
        transit_periods: [15, 255],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_229_935_173,
        bitnum: 8,
        legend_colour: 184,
        rating_colour: 184,
        weight: 16,
        multiplier: 0x100,
        classes: 16_400,
        initial_payment: 5120,
        transit_periods: [9, 255],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_398_031_692,
        bitnum: 9,
        legend_colour: 10,
        rating_colour: 10,
        weight: 16,
        multiplier: 0x100,
        classes: 32,
        initial_payment: 5688,
        transit_periods: [7, 255],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_447_119_957,
        bitnum: 10,
        legend_colour: 202,
        rating_colour: 202,
        weight: 2,
        multiplier: 0x100,
        classes: 8,
        initial_payment: 7509,
        transit_periods: [1, 32],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_196_379_204,
        bitnum: 10,
        legend_colour: 202,
        rating_colour: 202,
        weight: 8,
        multiplier: 0x100,
        classes: 8,
        initial_payment: 5802,
        transit_periods: [10, 40],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_145_651_533,
        bitnum: 10,
        legend_colour: 202,
        rating_colour: 202,
        weight: 2,
        multiplier: 0x100,
        classes: 8,
        initial_payment: 5802,
        transit_periods: [10, 255],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_346_457_682,
        bitnum: 11,
        legend_colour: 10,
        rating_colour: 10,
        weight: 16,
        multiplier: 0x100,
        classes: 32,
        initial_payment: 5461,
        transit_periods: [7, 60],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_179_602_756,
        bitnum: 12,
        legend_colour: 48,
        rating_colour: 48,
        weight: 16,
        multiplier: 0x100,
        classes: 8324,
        initial_payment: 5688,
        transit_periods: [0, 30],
        is_freight: true,
        town_acceptance_effect: 5,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_179_800_916,
        bitnum: 13,
        legend_colour: 208,
        rating_colour: 208,
        weight: 16,
        multiplier: 0x100,
        classes: 8336,
        initial_payment: 4209,
        transit_periods: [0, 15],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_129_271_877,
        bitnum: 14,
        legend_colour: 184,
        rating_colour: 184,
        weight: 16,
        multiplier: 0x100,
        classes: 16_400,
        initial_payment: 4892,
        transit_periods: [12, 255],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_463_899_218,
        bitnum: 15,
        legend_colour: 10,
        rating_colour: 10,
        weight: 16,
        multiplier: 0x100,
        classes: 8256,
        initial_payment: 4664,
        transit_periods: [20, 80],
        is_freight: true,
        town_acceptance_effect: 4,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_381_319_250,
        bitnum: 16,
        legend_colour: 6,
        rating_colour: 6,
        weight: 16,
        multiplier: 0x100,
        classes: 16_448,
        initial_payment: 4437,
        transit_periods: [2, 20],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_398_097_746,
        bitnum: 17,
        legend_colour: 6,
        rating_colour: 6,
        weight: 16,
        multiplier: 0x100,
        classes: 8208,
        initial_payment: 4437,
        transit_periods: [20, 255],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_414_486_355,
        bitnum: 18,
        legend_colour: 174,
        rating_colour: 174,
        weight: 2,
        multiplier: 0x100,
        classes: 32,
        initial_payment: 5574,
        transit_periods: [25, 255],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_111_577_684,
        bitnum: 19,
        legend_colour: 208,
        rating_colour: 208,
        weight: 4,
        multiplier: 0x100,
        classes: 32,
        initial_payment: 4322,
        transit_periods: [2, 30],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_398_228_308,
        bitnum: 20,
        legend_colour: 194,
        rating_colour: 194,
        weight: 5,
        multiplier: 0x200,
        classes: 4,
        initial_payment: 6144,
        transit_periods: [8, 40],
        is_freight: true,
        town_acceptance_effect: 3,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_414_481_478,
        bitnum: 21,
        legend_colour: 191,
        rating_colour: 191,
        weight: 16,
        multiplier: 0x100,
        classes: 16,
        initial_payment: 4778,
        transit_periods: [14, 60],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_129_270_337,
        bitnum: 22,
        legend_colour: 84,
        rating_colour: 84,
        weight: 16,
        multiplier: 0x100,
        classes: 64,
        initial_payment: 4892,
        transit_periods: [5, 75],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_129_595_716,
        bitnum: 23,
        legend_colour: 184,
        rating_colour: 184,
        weight: 16,
        multiplier: 0x100,
        classes: 16,
        initial_payment: 5005,
        transit_periods: [10, 25],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_112_883_788,
        bitnum: 24,
        legend_colour: 10,
        rating_colour: 10,
        weight: 1,
        multiplier: 0x100,
        classes: 32,
        initial_payment: 5077,
        transit_periods: [20, 80],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_347_179_348,
        bitnum: 25,
        legend_colour: 202,
        rating_colour: 202,
        weight: 16,
        multiplier: 0x100,
        classes: 64,
        initial_payment: 4664,
        transit_periods: [30, 255],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 1_180_320_850,
        bitnum: 26,
        legend_colour: 48,
        rating_colour: 48,
        weight: 2,
        multiplier: 0x100,
        classes: 32,
        initial_payment: 6250,
        transit_periods: [30, 50],
        is_freight: true,
        town_acceptance_effect: 5,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 4_294_967_295,
        bitnum: 0xFF,
        legend_colour: 1,
        rating_colour: 1,
        weight: 0,
        multiplier: 0x100,
        classes: 0,
        initial_payment: 5688,
        transit_periods: [0, 30],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
    CargoSpec {
        label: 4_294_967_295,
        bitnum: 0xFF,
        legend_colour: 184,
        rating_colour: 184,
        weight: 0,
        multiplier: 0x100,
        classes: 0,
        initial_payment: 5120,
        transit_periods: [9, 255],
        is_freight: true,
        town_acceptance_effect: 0,
        town_production_effect: 0,
        town_production_multiplier: 256,
        callback_mask: 0,
        current_payment: 0,
    },
];
pub(super) const CLIMATE_CARGO: [[usize; 12]; 4] = [
    [0, 1, 2, 3, 5, 6, 7, 10, 12, 13, 14, 33],
    [0, 1, 2, 3, 5, 6, 8, 10, 34, 17, 15, 18],
    [0, 22, 2, 4, 19, 6, 9, 11, 20, 21, 16, 18],
    [0, 23, 2, 24, 25, 26, 27, 28, 29, 30, 31, 32],
];
