// SPDX-License-Identifier: GPL-2.0-only
// Ported from OpenTTD 14ec60f248547d4d062a1160f0fc26d742319888 src/table/engines.h.
use super::Price;
use super::RailSpec;
pub(super) const VEHICLES: [RailSpec; 116] = [
    RailSpec {
        image_index: 2,
        railveh_type: 0,
        cost_factor: 7,
        max_speed: 64,
        power: 300,
        weight: 47,
        running_cost: 50,
        running_cost_class: Some(Price::RunningTrainSteam),
        capacity: 0,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 19,
        railveh_type: 0,
        cost_factor: 8,
        max_speed: 80,
        power: 600,
        weight: 65,
        running_cost: 65,
        running_cost_class: Some(Price::RunningTrainDiesel),
        capacity: 0,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 1,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 2,
        railveh_type: 0,
        cost_factor: 10,
        max_speed: 72,
        power: 400,
        weight: 85,
        running_cost: 90,
        running_cost_class: Some(Price::RunningTrainSteam),
        capacity: 0,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 0,
        railveh_type: 0,
        cost_factor: 15,
        max_speed: 96,
        power: 900,
        weight: 130,
        running_cost: 130,
        running_cost_class: Some(Price::RunningTrainSteam),
        capacity: 0,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 1,
        railveh_type: 0,
        cost_factor: 19,
        max_speed: 112,
        power: 1000,
        weight: 140,
        running_cost: 145,
        running_cost_class: Some(Price::RunningTrainSteam),
        capacity: 0,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 12,
        railveh_type: 0,
        cost_factor: 16,
        max_speed: 120,
        power: 1400,
        weight: 95,
        running_cost: 125,
        running_cost_class: Some(Price::RunningTrainDiesel),
        capacity: 0,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 1,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 14,
        railveh_type: 0,
        cost_factor: 20,
        max_speed: 152,
        power: 2000,
        weight: 120,
        running_cost: 135,
        running_cost_class: Some(Price::RunningTrainDiesel),
        capacity: 0,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 1,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 3,
        railveh_type: 0,
        cost_factor: 14,
        max_speed: 88,
        power: 1100,
        weight: 145,
        running_cost: 130,
        running_cost_class: Some(Price::RunningTrainSteam),
        capacity: 0,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 0,
        railveh_type: 0,
        cost_factor: 13,
        max_speed: 112,
        power: 1000,
        weight: 131,
        running_cost: 120,
        running_cost_class: Some(Price::RunningTrainSteam),
        capacity: 0,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 1,
        railveh_type: 0,
        cost_factor: 19,
        max_speed: 128,
        power: 1200,
        weight: 162,
        running_cost: 140,
        running_cost_class: Some(Price::RunningTrainSteam),
        capacity: 0,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 0,
        railveh_type: 0,
        cost_factor: 22,
        max_speed: 144,
        power: 1600,
        weight: 170,
        running_cost: 130,
        running_cost_class: Some(Price::RunningTrainSteam),
        capacity: 0,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 8,
        railveh_type: 1,
        cost_factor: 11,
        max_speed: 112,
        power: 600,
        weight: 32,
        running_cost: 85,
        running_cost_class: Some(Price::RunningTrainDiesel),
        capacity: 38,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 1,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 10,
        railveh_type: 1,
        cost_factor: 14,
        max_speed: 120,
        power: 700,
        weight: 38,
        running_cost: 70,
        running_cost_class: Some(Price::RunningTrainDiesel),
        capacity: 40,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 1,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 4,
        railveh_type: 0,
        cost_factor: 15,
        max_speed: 128,
        power: 1250,
        weight: 72,
        running_cost: 95,
        running_cost_class: Some(Price::RunningTrainDiesel),
        capacity: 0,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 1,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 5,
        railveh_type: 0,
        cost_factor: 17,
        max_speed: 144,
        power: 1750,
        weight: 101,
        running_cost: 120,
        running_cost_class: Some(Price::RunningTrainDiesel),
        capacity: 0,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 1,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 4,
        railveh_type: 0,
        cost_factor: 18,
        max_speed: 160,
        power: 2580,
        weight: 112,
        running_cost: 140,
        running_cost_class: Some(Price::RunningTrainDiesel),
        capacity: 0,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 1,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 14,
        railveh_type: 0,
        cost_factor: 23,
        max_speed: 96,
        power: 4000,
        weight: 150,
        running_cost: 135,
        running_cost_class: Some(Price::RunningTrainDiesel),
        capacity: 0,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 1,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 12,
        railveh_type: 0,
        cost_factor: 16,
        max_speed: 112,
        power: 2400,
        weight: 120,
        running_cost: 105,
        running_cost_class: Some(Price::RunningTrainDiesel),
        capacity: 0,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 1,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 13,
        railveh_type: 0,
        cost_factor: 30,
        max_speed: 112,
        power: 6600,
        weight: 207,
        running_cost: 155,
        running_cost_class: Some(Price::RunningTrainDiesel),
        capacity: 0,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 1,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 15,
        railveh_type: 0,
        cost_factor: 18,
        max_speed: 104,
        power: 1500,
        weight: 110,
        running_cost: 105,
        running_cost_class: Some(Price::RunningTrainDiesel),
        capacity: 0,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 1,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 16,
        railveh_type: 1,
        cost_factor: 35,
        max_speed: 160,
        power: 3500,
        weight: 95,
        running_cost: 205,
        running_cost_class: Some(Price::RunningTrainDiesel),
        capacity: 0,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 1,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 18,
        railveh_type: 0,
        cost_factor: 21,
        max_speed: 104,
        power: 2200,
        weight: 120,
        running_cost: 145,
        running_cost_class: Some(Price::RunningTrainDiesel),
        capacity: 0,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 1,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 6,
        railveh_type: 1,
        cost_factor: 20,
        max_speed: 200,
        power: 4500,
        weight: 70,
        running_cost: 190,
        running_cost_class: Some(Price::RunningTrainDiesel),
        capacity: 4,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 1,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 20,
        railveh_type: 0,
        cost_factor: 26,
        max_speed: 160,
        power: 3600,
        weight: 84,
        running_cost: 180,
        running_cost_class: Some(Price::RunningTrainElectric),
        capacity: 0,
        intended_railtypes: 2,
        railtypes: 2,
        engclass: 2,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 20,
        railveh_type: 0,
        cost_factor: 30,
        max_speed: 176,
        power: 5000,
        weight: 82,
        running_cost: 205,
        running_cost_class: Some(Price::RunningTrainElectric),
        capacity: 0,
        intended_railtypes: 2,
        railtypes: 2,
        engclass: 2,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 21,
        railveh_type: 1,
        cost_factor: 40,
        max_speed: 240,
        power: 7000,
        weight: 90,
        running_cost: 240,
        running_cost_class: Some(Price::RunningTrainElectric),
        capacity: 0,
        intended_railtypes: 2,
        railtypes: 2,
        engclass: 2,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 23,
        railveh_type: 1,
        cost_factor: 43,
        max_speed: 264,
        power: 8000,
        weight: 95,
        running_cost: 250,
        running_cost_class: Some(Price::RunningTrainElectric),
        capacity: 0,
        intended_railtypes: 2,
        railtypes: 2,
        engclass: 2,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 33,
        railveh_type: 2,
        cost_factor: 247,
        max_speed: 0,
        power: 0,
        weight: 25,
        running_cost: 0,
        running_cost_class: None,
        capacity: 40,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 35,
        railveh_type: 2,
        cost_factor: 228,
        max_speed: 0,
        power: 0,
        weight: 21,
        running_cost: 0,
        running_cost_class: None,
        capacity: 30,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 34,
        railveh_type: 2,
        cost_factor: 176,
        max_speed: 0,
        power: 0,
        weight: 18,
        running_cost: 0,
        running_cost_class: None,
        capacity: 30,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 36,
        railveh_type: 2,
        cost_factor: 200,
        max_speed: 0,
        power: 0,
        weight: 24,
        running_cost: 0,
        running_cost_class: None,
        capacity: 30,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 37,
        railveh_type: 2,
        cost_factor: 192,
        max_speed: 0,
        power: 0,
        weight: 20,
        running_cost: 0,
        running_cost_class: None,
        capacity: 25,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 38,
        railveh_type: 2,
        cost_factor: 190,
        max_speed: 0,
        power: 0,
        weight: 21,
        running_cost: 0,
        running_cost_class: None,
        capacity: 25,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 39,
        railveh_type: 2,
        cost_factor: 182,
        max_speed: 0,
        power: 0,
        weight: 19,
        running_cost: 0,
        running_cost_class: None,
        capacity: 30,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 40,
        railveh_type: 2,
        cost_factor: 181,
        max_speed: 0,
        power: 0,
        weight: 16,
        running_cost: 0,
        running_cost_class: None,
        capacity: 30,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 41,
        railveh_type: 2,
        cost_factor: 179,
        max_speed: 0,
        power: 0,
        weight: 19,
        running_cost: 0,
        running_cost_class: None,
        capacity: 30,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 42,
        railveh_type: 2,
        cost_factor: 196,
        max_speed: 0,
        power: 0,
        weight: 18,
        running_cost: 0,
        running_cost_class: None,
        capacity: 20,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 43,
        railveh_type: 2,
        cost_factor: 255,
        max_speed: 0,
        power: 0,
        weight: 30,
        running_cost: 0,
        running_cost_class: None,
        capacity: 20,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 44,
        railveh_type: 2,
        cost_factor: 191,
        max_speed: 0,
        power: 0,
        weight: 22,
        running_cost: 0,
        running_cost_class: None,
        capacity: 25,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 45,
        railveh_type: 2,
        cost_factor: 196,
        max_speed: 0,
        power: 0,
        weight: 18,
        running_cost: 0,
        running_cost_class: None,
        capacity: 20,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 46,
        railveh_type: 2,
        cost_factor: 179,
        max_speed: 0,
        power: 0,
        weight: 19,
        running_cost: 0,
        running_cost_class: None,
        capacity: 30,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 47,
        railveh_type: 2,
        cost_factor: 199,
        max_speed: 0,
        power: 0,
        weight: 25,
        running_cost: 0,
        running_cost_class: None,
        capacity: 25,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 48,
        railveh_type: 2,
        cost_factor: 182,
        max_speed: 0,
        power: 0,
        weight: 18,
        running_cost: 0,
        running_cost_class: None,
        capacity: 25,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 49,
        railveh_type: 2,
        cost_factor: 185,
        max_speed: 0,
        power: 0,
        weight: 19,
        running_cost: 0,
        running_cost_class: None,
        capacity: 21,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 50,
        railveh_type: 2,
        cost_factor: 176,
        max_speed: 0,
        power: 0,
        weight: 19,
        running_cost: 0,
        running_cost_class: None,
        capacity: 30,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 51,
        railveh_type: 2,
        cost_factor: 178,
        max_speed: 0,
        power: 0,
        weight: 20,
        running_cost: 0,
        running_cost_class: None,
        capacity: 30,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 52,
        railveh_type: 2,
        cost_factor: 192,
        max_speed: 0,
        power: 0,
        weight: 20,
        running_cost: 0,
        running_cost_class: None,
        capacity: 30,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 53,
        railveh_type: 2,
        cost_factor: 190,
        max_speed: 0,
        power: 0,
        weight: 21,
        running_cost: 0,
        running_cost_class: None,
        capacity: 20,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 54,
        railveh_type: 2,
        cost_factor: 182,
        max_speed: 0,
        power: 0,
        weight: 24,
        running_cost: 0,
        running_cost_class: None,
        capacity: 25,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 55,
        railveh_type: 2,
        cost_factor: 181,
        max_speed: 0,
        power: 0,
        weight: 21,
        running_cost: 0,
        running_cost_class: None,
        capacity: 25,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 56,
        railveh_type: 2,
        cost_factor: 183,
        max_speed: 0,
        power: 0,
        weight: 21,
        running_cost: 0,
        running_cost_class: None,
        capacity: 20,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 57,
        railveh_type: 2,
        cost_factor: 196,
        max_speed: 0,
        power: 0,
        weight: 18,
        running_cost: 0,
        running_cost_class: None,
        capacity: 22,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 58,
        railveh_type: 2,
        cost_factor: 193,
        max_speed: 0,
        power: 0,
        weight: 18,
        running_cost: 0,
        running_cost_class: None,
        capacity: 25,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 59,
        railveh_type: 2,
        cost_factor: 191,
        max_speed: 0,
        power: 0,
        weight: 18,
        running_cost: 0,
        running_cost_class: None,
        capacity: 30,
        intended_railtypes: 1,
        railtypes: 1,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 25,
        railveh_type: 0,
        cost_factor: 52,
        max_speed: 304,
        power: 9000,
        weight: 95,
        running_cost: 230,
        running_cost_class: Some(Price::RunningTrainElectric),
        capacity: 0,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 3,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 26,
        railveh_type: 1,
        cost_factor: 60,
        max_speed: 336,
        power: 10000,
        weight: 85,
        running_cost: 240,
        running_cost_class: Some(Price::RunningTrainElectric),
        capacity: 25,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 3,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 26,
        railveh_type: 0,
        cost_factor: 53,
        max_speed: 320,
        power: 5000,
        weight: 95,
        running_cost: 230,
        running_cost_class: Some(Price::RunningTrainElectric),
        capacity: 0,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 3,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 60,
        railveh_type: 2,
        cost_factor: 247,
        max_speed: 0,
        power: 0,
        weight: 25,
        running_cost: 0,
        running_cost_class: None,
        capacity: 45,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 62,
        railveh_type: 2,
        cost_factor: 228,
        max_speed: 0,
        power: 0,
        weight: 21,
        running_cost: 0,
        running_cost_class: None,
        capacity: 35,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 61,
        railveh_type: 2,
        cost_factor: 176,
        max_speed: 0,
        power: 0,
        weight: 18,
        running_cost: 0,
        running_cost_class: None,
        capacity: 35,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 63,
        railveh_type: 2,
        cost_factor: 200,
        max_speed: 0,
        power: 0,
        weight: 24,
        running_cost: 0,
        running_cost_class: None,
        capacity: 35,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 64,
        railveh_type: 2,
        cost_factor: 192,
        max_speed: 0,
        power: 0,
        weight: 20,
        running_cost: 0,
        running_cost_class: None,
        capacity: 30,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 65,
        railveh_type: 2,
        cost_factor: 190,
        max_speed: 0,
        power: 0,
        weight: 21,
        running_cost: 0,
        running_cost_class: None,
        capacity: 30,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 66,
        railveh_type: 2,
        cost_factor: 182,
        max_speed: 0,
        power: 0,
        weight: 19,
        running_cost: 0,
        running_cost_class: None,
        capacity: 35,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 67,
        railveh_type: 2,
        cost_factor: 181,
        max_speed: 0,
        power: 0,
        weight: 16,
        running_cost: 0,
        running_cost_class: None,
        capacity: 35,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 68,
        railveh_type: 2,
        cost_factor: 179,
        max_speed: 0,
        power: 0,
        weight: 19,
        running_cost: 0,
        running_cost_class: None,
        capacity: 35,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 69,
        railveh_type: 2,
        cost_factor: 196,
        max_speed: 0,
        power: 0,
        weight: 18,
        running_cost: 0,
        running_cost_class: None,
        capacity: 25,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 70,
        railveh_type: 2,
        cost_factor: 255,
        max_speed: 0,
        power: 0,
        weight: 30,
        running_cost: 0,
        running_cost_class: None,
        capacity: 25,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 71,
        railveh_type: 2,
        cost_factor: 191,
        max_speed: 0,
        power: 0,
        weight: 22,
        running_cost: 0,
        running_cost_class: None,
        capacity: 30,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 72,
        railveh_type: 2,
        cost_factor: 196,
        max_speed: 0,
        power: 0,
        weight: 18,
        running_cost: 0,
        running_cost_class: None,
        capacity: 25,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 73,
        railveh_type: 2,
        cost_factor: 179,
        max_speed: 0,
        power: 0,
        weight: 19,
        running_cost: 0,
        running_cost_class: None,
        capacity: 35,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 47,
        railveh_type: 2,
        cost_factor: 199,
        max_speed: 0,
        power: 0,
        weight: 25,
        running_cost: 0,
        running_cost_class: None,
        capacity: 30,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 48,
        railveh_type: 2,
        cost_factor: 182,
        max_speed: 0,
        power: 0,
        weight: 18,
        running_cost: 0,
        running_cost_class: None,
        capacity: 30,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 49,
        railveh_type: 2,
        cost_factor: 185,
        max_speed: 0,
        power: 0,
        weight: 19,
        running_cost: 0,
        running_cost_class: None,
        capacity: 26,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 50,
        railveh_type: 2,
        cost_factor: 176,
        max_speed: 0,
        power: 0,
        weight: 19,
        running_cost: 0,
        running_cost_class: None,
        capacity: 35,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 51,
        railveh_type: 2,
        cost_factor: 178,
        max_speed: 0,
        power: 0,
        weight: 20,
        running_cost: 0,
        running_cost_class: None,
        capacity: 35,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 52,
        railveh_type: 2,
        cost_factor: 192,
        max_speed: 0,
        power: 0,
        weight: 20,
        running_cost: 0,
        running_cost_class: None,
        capacity: 35,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 53,
        railveh_type: 2,
        cost_factor: 190,
        max_speed: 0,
        power: 0,
        weight: 21,
        running_cost: 0,
        running_cost_class: None,
        capacity: 25,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 54,
        railveh_type: 2,
        cost_factor: 182,
        max_speed: 0,
        power: 0,
        weight: 24,
        running_cost: 0,
        running_cost_class: None,
        capacity: 30,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 55,
        railveh_type: 2,
        cost_factor: 181,
        max_speed: 0,
        power: 0,
        weight: 21,
        running_cost: 0,
        running_cost_class: None,
        capacity: 30,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 56,
        railveh_type: 2,
        cost_factor: 183,
        max_speed: 0,
        power: 0,
        weight: 21,
        running_cost: 0,
        running_cost_class: None,
        capacity: 25,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 57,
        railveh_type: 2,
        cost_factor: 196,
        max_speed: 0,
        power: 0,
        weight: 18,
        running_cost: 0,
        running_cost_class: None,
        capacity: 27,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 58,
        railveh_type: 2,
        cost_factor: 193,
        max_speed: 0,
        power: 0,
        weight: 18,
        running_cost: 0,
        running_cost_class: None,
        capacity: 30,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 59,
        railveh_type: 2,
        cost_factor: 191,
        max_speed: 0,
        power: 0,
        weight: 18,
        running_cost: 0,
        running_cost_class: None,
        capacity: 35,
        intended_railtypes: 4,
        railtypes: 4,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 28,
        railveh_type: 0,
        cost_factor: 70,
        max_speed: 400,
        power: 10000,
        weight: 105,
        running_cost: 250,
        running_cost_class: Some(Price::RunningTrainElectric),
        capacity: 0,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 4,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 29,
        railveh_type: 0,
        cost_factor: 74,
        max_speed: 448,
        power: 12000,
        weight: 120,
        running_cost: 253,
        running_cost_class: Some(Price::RunningTrainElectric),
        capacity: 0,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 4,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 30,
        railveh_type: 0,
        cost_factor: 82,
        max_speed: 480,
        power: 15000,
        weight: 130,
        running_cost: 254,
        running_cost_class: Some(Price::RunningTrainElectric),
        capacity: 0,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 4,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 31,
        railveh_type: 1,
        cost_factor: 95,
        max_speed: 640,
        power: 20000,
        weight: 150,
        running_cost: 255,
        running_cost_class: Some(Price::RunningTrainElectric),
        capacity: 0,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 4,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 28,
        railveh_type: 0,
        cost_factor: 70,
        max_speed: 480,
        power: 10000,
        weight: 120,
        running_cost: 250,
        running_cost_class: Some(Price::RunningTrainElectric),
        capacity: 0,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 4,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 60,
        railveh_type: 2,
        cost_factor: 247,
        max_speed: 0,
        power: 0,
        weight: 25,
        running_cost: 0,
        running_cost_class: None,
        capacity: 47,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 62,
        railveh_type: 2,
        cost_factor: 228,
        max_speed: 0,
        power: 0,
        weight: 21,
        running_cost: 0,
        running_cost_class: None,
        capacity: 37,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 61,
        railveh_type: 2,
        cost_factor: 176,
        max_speed: 0,
        power: 0,
        weight: 18,
        running_cost: 0,
        running_cost_class: None,
        capacity: 37,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 63,
        railveh_type: 2,
        cost_factor: 200,
        max_speed: 0,
        power: 0,
        weight: 24,
        running_cost: 0,
        running_cost_class: None,
        capacity: 37,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 64,
        railveh_type: 2,
        cost_factor: 192,
        max_speed: 0,
        power: 0,
        weight: 20,
        running_cost: 0,
        running_cost_class: None,
        capacity: 32,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 65,
        railveh_type: 2,
        cost_factor: 190,
        max_speed: 0,
        power: 0,
        weight: 21,
        running_cost: 0,
        running_cost_class: None,
        capacity: 32,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 66,
        railveh_type: 2,
        cost_factor: 182,
        max_speed: 0,
        power: 0,
        weight: 19,
        running_cost: 0,
        running_cost_class: None,
        capacity: 37,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 67,
        railveh_type: 2,
        cost_factor: 181,
        max_speed: 0,
        power: 0,
        weight: 16,
        running_cost: 0,
        running_cost_class: None,
        capacity: 37,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 68,
        railveh_type: 2,
        cost_factor: 179,
        max_speed: 0,
        power: 0,
        weight: 19,
        running_cost: 0,
        running_cost_class: None,
        capacity: 37,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 69,
        railveh_type: 2,
        cost_factor: 196,
        max_speed: 0,
        power: 0,
        weight: 18,
        running_cost: 0,
        running_cost_class: None,
        capacity: 27,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 70,
        railveh_type: 2,
        cost_factor: 255,
        max_speed: 0,
        power: 0,
        weight: 30,
        running_cost: 0,
        running_cost_class: None,
        capacity: 27,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 71,
        railveh_type: 2,
        cost_factor: 191,
        max_speed: 0,
        power: 0,
        weight: 22,
        running_cost: 0,
        running_cost_class: None,
        capacity: 32,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 72,
        railveh_type: 2,
        cost_factor: 196,
        max_speed: 0,
        power: 0,
        weight: 18,
        running_cost: 0,
        running_cost_class: None,
        capacity: 27,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 73,
        railveh_type: 2,
        cost_factor: 179,
        max_speed: 0,
        power: 0,
        weight: 19,
        running_cost: 0,
        running_cost_class: None,
        capacity: 37,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 47,
        railveh_type: 2,
        cost_factor: 199,
        max_speed: 0,
        power: 0,
        weight: 25,
        running_cost: 0,
        running_cost_class: None,
        capacity: 32,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 48,
        railveh_type: 2,
        cost_factor: 182,
        max_speed: 0,
        power: 0,
        weight: 18,
        running_cost: 0,
        running_cost_class: None,
        capacity: 32,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 49,
        railveh_type: 2,
        cost_factor: 185,
        max_speed: 0,
        power: 0,
        weight: 19,
        running_cost: 0,
        running_cost_class: None,
        capacity: 28,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 50,
        railveh_type: 2,
        cost_factor: 176,
        max_speed: 0,
        power: 0,
        weight: 19,
        running_cost: 0,
        running_cost_class: None,
        capacity: 37,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 51,
        railveh_type: 2,
        cost_factor: 178,
        max_speed: 0,
        power: 0,
        weight: 20,
        running_cost: 0,
        running_cost_class: None,
        capacity: 37,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 52,
        railveh_type: 2,
        cost_factor: 192,
        max_speed: 0,
        power: 0,
        weight: 20,
        running_cost: 0,
        running_cost_class: None,
        capacity: 37,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 53,
        railveh_type: 2,
        cost_factor: 190,
        max_speed: 0,
        power: 0,
        weight: 21,
        running_cost: 0,
        running_cost_class: None,
        capacity: 27,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 54,
        railveh_type: 2,
        cost_factor: 182,
        max_speed: 0,
        power: 0,
        weight: 24,
        running_cost: 0,
        running_cost_class: None,
        capacity: 32,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 55,
        railveh_type: 2,
        cost_factor: 181,
        max_speed: 0,
        power: 0,
        weight: 21,
        running_cost: 0,
        running_cost_class: None,
        capacity: 32,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 56,
        railveh_type: 2,
        cost_factor: 183,
        max_speed: 0,
        power: 0,
        weight: 21,
        running_cost: 0,
        running_cost_class: None,
        capacity: 27,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 57,
        railveh_type: 2,
        cost_factor: 196,
        max_speed: 0,
        power: 0,
        weight: 18,
        running_cost: 0,
        running_cost_class: None,
        capacity: 29,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 58,
        railveh_type: 2,
        cost_factor: 193,
        max_speed: 0,
        power: 0,
        weight: 18,
        running_cost: 0,
        running_cost_class: None,
        capacity: 32,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
    RailSpec {
        image_index: 59,
        railveh_type: 2,
        cost_factor: 191,
        max_speed: 0,
        power: 0,
        weight: 18,
        running_cost: 0,
        running_cost_class: None,
        capacity: 37,
        intended_railtypes: 8,
        railtypes: 8,
        engclass: 0,
        ..RailSpec::DEFAULT
    },
];
