// SPDX-License-Identifier: GPL-2.0-only
// Ported from OpenTTD 14ec60f248547d4d062a1160f0fc26d742319888 src/table/engines.h.
use super::Price;
use super::RoadSpec;
pub(super) const VEHICLES: [RoadSpec; 88] = [
    RoadSpec {
        image_index: 0,
        cost_factor: 120,
        running_cost: 91,
        sfx: 23,
        max_speed: 112,
        capacity: 31,
        weight: 42,
        power: 9,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 17,
        cost_factor: 140,
        running_cost: 128,
        sfx: 26,
        max_speed: 176,
        capacity: 35,
        weight: 60,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 17,
        cost_factor: 150,
        running_cost: 178,
        sfx: 25,
        max_speed: 224,
        capacity: 37,
        weight: 70,
        power: 15,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 34,
        cost_factor: 160,
        running_cost: 240,
        sfx: 25,
        max_speed: 255,
        capacity: 40,
        weight: 100,
        power: 25,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 51,
        cost_factor: 120,
        running_cost: 91,
        sfx: 60,
        max_speed: 112,
        capacity: 30,
        weight: 42,
        power: 9,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 51,
        cost_factor: 140,
        running_cost: 171,
        sfx: 62,
        max_speed: 192,
        capacity: 35,
        weight: 60,
        power: 15,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 51,
        cost_factor: 160,
        running_cost: 240,
        sfx: 60,
        max_speed: 240,
        capacity: 38,
        weight: 90,
        power: 25,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 1,
        cost_factor: 108,
        running_cost: 90,
        sfx: 23,
        max_speed: 96,
        capacity: 20,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 18,
        cost_factor: 128,
        running_cost: 168,
        sfx: 23,
        max_speed: 176,
        capacity: 25,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 35,
        cost_factor: 138,
        running_cost: 240,
        sfx: 23,
        max_speed: 224,
        capacity: 28,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 2,
        cost_factor: 115,
        running_cost: 90,
        sfx: 23,
        max_speed: 96,
        capacity: 22,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 19,
        cost_factor: 135,
        running_cost: 168,
        sfx: 23,
        max_speed: 176,
        capacity: 28,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 36,
        cost_factor: 145,
        running_cost: 240,
        sfx: 23,
        max_speed: 224,
        capacity: 30,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 57,
        cost_factor: 115,
        running_cost: 90,
        sfx: 62,
        max_speed: 96,
        capacity: 22,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 57,
        cost_factor: 135,
        running_cost: 168,
        sfx: 60,
        max_speed: 176,
        capacity: 28,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 57,
        cost_factor: 145,
        running_cost: 240,
        sfx: 62,
        max_speed: 224,
        capacity: 30,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 3,
        cost_factor: 110,
        running_cost: 90,
        sfx: 23,
        max_speed: 96,
        capacity: 21,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 20,
        cost_factor: 140,
        running_cost: 168,
        sfx: 23,
        max_speed: 176,
        capacity: 25,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 37,
        cost_factor: 150,
        running_cost: 240,
        sfx: 23,
        max_speed: 224,
        capacity: 27,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 4,
        cost_factor: 105,
        running_cost: 90,
        sfx: 23,
        max_speed: 96,
        capacity: 14,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 21,
        cost_factor: 130,
        running_cost: 168,
        sfx: 23,
        max_speed: 176,
        capacity: 16,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 38,
        cost_factor: 140,
        running_cost: 240,
        sfx: 23,
        max_speed: 224,
        capacity: 18,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 5,
        cost_factor: 107,
        running_cost: 90,
        sfx: 23,
        max_speed: 96,
        capacity: 14,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 22,
        cost_factor: 130,
        running_cost: 168,
        sfx: 23,
        max_speed: 176,
        capacity: 16,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 39,
        cost_factor: 140,
        running_cost: 240,
        sfx: 23,
        max_speed: 224,
        capacity: 18,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 6,
        cost_factor: 114,
        running_cost: 90,
        sfx: 23,
        max_speed: 96,
        capacity: 20,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 23,
        cost_factor: 133,
        running_cost: 168,
        sfx: 23,
        max_speed: 176,
        capacity: 25,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 40,
        cost_factor: 143,
        running_cost: 240,
        sfx: 23,
        max_speed: 224,
        capacity: 30,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 7,
        cost_factor: 118,
        running_cost: 90,
        sfx: 23,
        max_speed: 96,
        capacity: 20,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 24,
        cost_factor: 137,
        running_cost: 168,
        sfx: 23,
        max_speed: 176,
        capacity: 22,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 41,
        cost_factor: 147,
        running_cost: 240,
        sfx: 23,
        max_speed: 224,
        capacity: 24,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 8,
        cost_factor: 121,
        running_cost: 90,
        sfx: 23,
        max_speed: 96,
        capacity: 22,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 25,
        cost_factor: 140,
        running_cost: 168,
        sfx: 23,
        max_speed: 176,
        capacity: 25,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 42,
        cost_factor: 150,
        running_cost: 240,
        sfx: 23,
        max_speed: 224,
        capacity: 27,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 9,
        cost_factor: 112,
        running_cost: 90,
        sfx: 23,
        max_speed: 96,
        capacity: 15,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 26,
        cost_factor: 135,
        running_cost: 168,
        sfx: 23,
        max_speed: 176,
        capacity: 18,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 43,
        cost_factor: 145,
        running_cost: 240,
        sfx: 23,
        max_speed: 224,
        capacity: 20,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 10,
        cost_factor: 145,
        running_cost: 90,
        sfx: 23,
        max_speed: 96,
        capacity: 12,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 27,
        cost_factor: 170,
        running_cost: 168,
        sfx: 23,
        max_speed: 176,
        capacity: 15,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 44,
        cost_factor: 180,
        running_cost: 240,
        sfx: 23,
        max_speed: 224,
        capacity: 16,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 11,
        cost_factor: 112,
        running_cost: 90,
        sfx: 23,
        max_speed: 96,
        capacity: 17,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 28,
        cost_factor: 134,
        running_cost: 168,
        sfx: 23,
        max_speed: 176,
        capacity: 20,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 45,
        cost_factor: 144,
        running_cost: 240,
        sfx: 23,
        max_speed: 224,
        capacity: 22,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 12,
        cost_factor: 112,
        running_cost: 90,
        sfx: 23,
        max_speed: 96,
        capacity: 15,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 29,
        cost_factor: 135,
        running_cost: 168,
        sfx: 23,
        max_speed: 176,
        capacity: 18,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 46,
        cost_factor: 145,
        running_cost: 240,
        sfx: 23,
        max_speed: 224,
        capacity: 20,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 13,
        cost_factor: 121,
        running_cost: 90,
        sfx: 23,
        max_speed: 96,
        capacity: 22,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 30,
        cost_factor: 140,
        running_cost: 168,
        sfx: 23,
        max_speed: 176,
        capacity: 25,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 47,
        cost_factor: 150,
        running_cost: 240,
        sfx: 23,
        max_speed: 224,
        capacity: 27,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 14,
        cost_factor: 111,
        running_cost: 90,
        sfx: 23,
        max_speed: 96,
        capacity: 21,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 31,
        cost_factor: 141,
        running_cost: 168,
        sfx: 23,
        max_speed: 176,
        capacity: 25,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 48,
        cost_factor: 151,
        running_cost: 240,
        sfx: 23,
        max_speed: 224,
        capacity: 27,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 15,
        cost_factor: 118,
        running_cost: 90,
        sfx: 23,
        max_speed: 96,
        capacity: 18,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 32,
        cost_factor: 148,
        running_cost: 168,
        sfx: 23,
        max_speed: 176,
        capacity: 20,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 49,
        cost_factor: 158,
        running_cost: 240,
        sfx: 23,
        max_speed: 224,
        capacity: 23,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 16,
        cost_factor: 117,
        running_cost: 90,
        sfx: 23,
        max_speed: 96,
        capacity: 17,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 33,
        cost_factor: 147,
        running_cost: 168,
        sfx: 23,
        max_speed: 176,
        capacity: 19,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 50,
        cost_factor: 157,
        running_cost: 240,
        sfx: 23,
        max_speed: 224,
        capacity: 22,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 52,
        cost_factor: 117,
        running_cost: 90,
        sfx: 63,
        max_speed: 96,
        capacity: 17,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 52,
        cost_factor: 147,
        running_cost: 168,
        sfx: 64,
        max_speed: 176,
        capacity: 19,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 52,
        cost_factor: 157,
        running_cost: 240,
        sfx: 63,
        max_speed: 224,
        capacity: 22,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 53,
        cost_factor: 117,
        running_cost: 90,
        sfx: 64,
        max_speed: 96,
        capacity: 17,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 53,
        cost_factor: 147,
        running_cost: 168,
        sfx: 63,
        max_speed: 176,
        capacity: 19,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 53,
        cost_factor: 157,
        running_cost: 240,
        sfx: 64,
        max_speed: 224,
        capacity: 22,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 54,
        cost_factor: 117,
        running_cost: 90,
        sfx: 63,
        max_speed: 96,
        capacity: 17,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 54,
        cost_factor: 147,
        running_cost: 168,
        sfx: 64,
        max_speed: 176,
        capacity: 19,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 54,
        cost_factor: 157,
        running_cost: 240,
        sfx: 63,
        max_speed: 224,
        capacity: 22,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 55,
        cost_factor: 117,
        running_cost: 90,
        sfx: 64,
        max_speed: 96,
        capacity: 17,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 55,
        cost_factor: 147,
        running_cost: 168,
        sfx: 63,
        max_speed: 176,
        capacity: 19,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 55,
        cost_factor: 157,
        running_cost: 240,
        sfx: 64,
        max_speed: 224,
        capacity: 22,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 56,
        cost_factor: 117,
        running_cost: 90,
        sfx: 63,
        max_speed: 96,
        capacity: 17,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 56,
        cost_factor: 147,
        running_cost: 168,
        sfx: 64,
        max_speed: 176,
        capacity: 19,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 56,
        cost_factor: 157,
        running_cost: 240,
        sfx: 63,
        max_speed: 224,
        capacity: 22,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 58,
        cost_factor: 117,
        running_cost: 90,
        sfx: 64,
        max_speed: 96,
        capacity: 17,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 58,
        cost_factor: 147,
        running_cost: 168,
        sfx: 63,
        max_speed: 176,
        capacity: 19,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 58,
        cost_factor: 157,
        running_cost: 240,
        sfx: 64,
        max_speed: 224,
        capacity: 22,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 59,
        cost_factor: 117,
        running_cost: 90,
        sfx: 63,
        max_speed: 96,
        capacity: 17,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 59,
        cost_factor: 147,
        running_cost: 168,
        sfx: 64,
        max_speed: 176,
        capacity: 19,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 59,
        cost_factor: 157,
        running_cost: 240,
        sfx: 63,
        max_speed: 224,
        capacity: 22,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 60,
        cost_factor: 117,
        running_cost: 90,
        sfx: 64,
        max_speed: 96,
        capacity: 17,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 60,
        cost_factor: 147,
        running_cost: 168,
        sfx: 63,
        max_speed: 176,
        capacity: 19,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 60,
        cost_factor: 157,
        running_cost: 240,
        sfx: 64,
        max_speed: 224,
        capacity: 22,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 61,
        cost_factor: 117,
        running_cost: 90,
        sfx: 63,
        max_speed: 96,
        capacity: 17,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 61,
        cost_factor: 147,
        running_cost: 168,
        sfx: 64,
        max_speed: 176,
        capacity: 19,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 61,
        cost_factor: 157,
        running_cost: 240,
        sfx: 63,
        max_speed: 224,
        capacity: 22,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 62,
        cost_factor: 117,
        running_cost: 90,
        sfx: 64,
        max_speed: 96,
        capacity: 17,
        weight: 38,
        power: 12,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 62,
        cost_factor: 147,
        running_cost: 168,
        sfx: 63,
        max_speed: 176,
        capacity: 19,
        weight: 48,
        power: 22,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
    RoadSpec {
        image_index: 62,
        cost_factor: 157,
        running_cost: 240,
        sfx: 64,
        max_speed: 224,
        capacity: 22,
        weight: 69,
        power: 45,
        running_cost_class: Some(Price::RunningRoadveh),
        ..RoadSpec::DEFAULT
    },
];
